apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - access-proxy.yaml
  - secrets.sops.yaml
  - pvc.yaml
  - workloads.yaml
  - services.yaml
  - networkpolicy.yaml
  - route.yaml
