apiVersion: v1
kind: Secret
metadata:
    name: mcphub-secrets
    namespace: apps
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:nq/swMBMpuR8h9lXn46E6A==,iv:4zaFECbtN+CaZNhpoVHPS/CFVy99mp7P38myJZBua/E=,tag:TSZNmidGkY4z3f8tNoGZiQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:f946794UOeYTGUVBr1epyg==,iv:TEA1zmm1+9BxzEt2trWNQKqWPZutk2/MeKpYZF04DRc=,tag:5/Owand5CURVy1RARIs4wQ==,type:str]
    database-url: ENC[AES256_GCM,data:K9Q/j6cDQsYZ5khRZ/yU0iZS2ZZ6Xcda0gM4RlW4EpKjle/KV3yXAQCBL3TSDlowl4wwWWHL3YfbdCoGcijVqjxPP3Obs4zKyjkUjVwMRzM=,iv:YnzDGi7gdLHQ8QrQCJBVd7DF0zuOJVmjrv6L3sg7su8=,tag:ZnJn52kjGBOM8BvsUG+Flg==,type:str]
stringData:
    jwt-secret: ENC[AES256_GCM,data:lcGqGaVpTTn8Etc/Ce8w4ad+J5kK/+DAgyp4X3PIkTHSVV4d31+N2XpvOlnSdQuDozX95ydnPUEAulI1erXtyQ==,iv:m3lI9hFeMgI/xZWnKC3tXMJqC7Lx+BA0/PRiM1V4f7Q=,tag:8u+x8/YBwGHcVdoOo4ELFA==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:8WVMgVZAgyoD4tE4JNWGJ2ibwU7tNIO4OO/863sRuiKQ37yPePPt0qoTuH7mf/1A/6y1NoZUAnRItt4HiqBWeg==,iv:uw+/XnA7OOa6HZsMGmv7fdu1yPqwpWjD1FppROoXygU=,tag:PFpSFHzkvlbHUKNauoGo9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cEhWS1RoV2VpTWVFSUh2
            QlB1U2Z4VlVSSU02OGtKa1c3b1NCSlc1ZVZnCmlDZDBEbXM4ajQyY29aRlNiU3RB
            bEFtQnlMTEdlcHZRSHQvaDM3a1VVLzgKLS0tIEpxY2NUY3diWEptdm0wRHhieXND
            bkJuOFBnOCtGMGJMeUN1bUJVZWpuMEUKgKqcgTV/wQOu/e2+kvSYdnvPiiSono+Q
            VPa+ZlnOyMgSFiCorHP1DQUeFYWoOfvWa2ukRYM96EKdUa/hZ4U6Tg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T02:09:55Z"
    mac: ENC[AES256_GCM,data:7jmGNAD+Wl4EQUcE4dKHR58N7YW9bF+A3389eP3On5jPhlro0Pmr8sg3nq47CpfCjHrk8k0SMOubZt3CWJcpMbAWTquYpUKBJw8YjYImDKsVLZWU6uHtxFA4ZPtxp52q07mKWTcmtlSfRxt8feRlW8yHmkv2Rw2WYB06sMvkOtM=,iv:pm4Ow/cGN9ME0HIgyPJcMSLjXa7BAqmiznayexoiJV4=,tag:wcZ3F0rwFnLCQpmCxNsqOA==,type:str]
    version: 3.13.2
