apiVersion: v1
kind: Secret
metadata:
    name: mcphub-secrets
    namespace: apps
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:nq/swMBMpuR8h9lXn46E6A==,iv:4zaFECbtN+CaZNhpoVHPS/CFVy99mp7P38myJZBua/E=,tag:TSZNmidGkY4z3f8tNoGZiQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:f946794UOeYTGUVBr1epyg==,iv:TEA1zmm1+9BxzEt2trWNQKqWPZutk2/MeKpYZF04DRc=,tag:5/Owand5CURVy1RARIs4wQ==,type:str]
    database-url: ENC[AES256_GCM,data:K9Q/j6cDQsYZ5khRZ/yU0iZS2ZZ6Xcda0gM4RlW4EpKjle/KV3yXAQCBL3TSDlowl4wwWWHL3YfbdCoGcijVqjxPP3Obs4zKyjkUjVwMRzM=,iv:YnzDGi7gdLHQ8QrQCJBVd7DF0zuOJVmjrv6L3sg7su8=,tag:ZnJn52kjGBOM8BvsUG+Flg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cEhWS1RoV2VpTWVFSUh2
            QlB1U2Z4VlVSSU02OGtKa1c3b1NCSlc1ZVZnCmlDZDBEbXM4ajQyY29aRlNiU3RB
            bEFtQnlMTEdlcHZRSHQvaDM3a1VVLzgKLS0tIEpxY2NUY3diWEptdm0wRHhieXND
            bkJuOFBnOCtGMGJMeUN1bUJVZWpuMEUKgKqcgTV/wQOu/e2+kvSYdnvPiiSono+Q
            VPa+ZlnOyMgSFiCorHP1DQUeFYWoOfvWa2ukRYM96EKdUa/hZ4U6Tg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T01:46:22Z"
    mac: ENC[AES256_GCM,data:Kg8PIulkY6I0xX+V0y+VywlzJKjPiD7nM841SyE2gvM7l0hQmTQ2K2lM/Eydn+KpnzV9awteJ5jnF3ukZmLpJ6aegQV6zoTT1+Ie6SO19qKIH8LpF+NkH3UB8s7QXZSnHhM/bc0p3NDV8svtxLbK48lkt/CqX1rz7U4HGRJkBAQ=,iv:Be/t1cuDaRprrMbxzMWlInS5j+QQcjqNGohSNMAdTUU=,tag:BJb6TAUyBGwf5820jbwLpQ==,type:str]
    version: 3.13.2
