apiVersion: v1
kind: Secret
metadata:
    name: mcphub-secrets
    namespace: apps
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:lWKEojvERF0AhiFyrHUWbA==,iv:2Kj25cxdd7lkMwXwkQ2jf9XUD7CsLZ95cgVIDZ7EmSo=,tag:k6/iFL6/zKnbOIQx9dTanA==,type:str]
    postgres-password: ENC[AES256_GCM,data:hS5t2V0HyBeCoa7SxfdhCA==,iv:NuTSR6CtWE3lhd4L4GOi/kAONZrtY/9nKqxhuL1j9JI=,tag:lcs/TiKSNskcrsRB/ePVqw==,type:str]
    database-url: ENC[AES256_GCM,data:uRL5bQK8IkL0rrRoV1glI8bZ7g0JVU1nK2KnXLmCkeVzxAKX73fKWoZZZaVYlvtHj7xHdbdFhJBCVtJo++0Ey6CxGF5sOa1lxYs5K7rGF0wMdjjM4Q==,iv:nbLn4UswvO9fQHEqPgQqD4AQueUDchcEiGlxqFYt6P4=,tag:H/2SlJTvDDrngoUDasFvBg==,type:str]
stringData:
    jwt-secret: ENC[AES256_GCM,data:t+O7lSuetSlK27kfFeCi98eVxFVcyTZsJ/8C9C8yVEJUBtdMYknMiS6GBq1EkFGZBVfo6rxWKY1uv8NQ+Pasgg==,iv:dqGNGg/Hah/y6X6+KlQjxqPL+/k+qcaecCmeXz9PAnk=,tag:3cY95cRgsM3EFOOJa9ZIMw==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:5Q7Tgpmj9Gi0Eyf+W0Ev1VCDGj/cdTr01mbFUuclKhfkCVy/KH20lc+CUPaWByrFdvA1vzcuoeTnts5Uk5pksA==,iv:yHbcJCLFndfxxCO6prtqFNyXkpB+Mq8osPB8GI378Kg=,tag:3bnb+Ckp73uVHCAw0eCRFA==,type:str]
    better-auth-secret: ENC[AES256_GCM,data:FpohXfUyqeSpSFpnSRuiFWvpEUxIhfYJ6UAB8EYxSTJSLVn6z9JoBwnzlZGuHxVwQqseWF6fs2V4UJQ0qD61Xw==,iv:nox+L54PhXRs+G7Chd/sp6Y+o0qQGfz4FI9VmTtfX+s=,tag:PRgiDkl9GpHsdtNCBF6STg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTFNhNVlmSWV3a3N0V295
            Z0F4UzQ4SUNNb3gvaFQ4MTZUcU94UjQxd0E0CllqOGZGMTZ6S0dvUUQrMWtaWlE0
            M2lUYlNPSEwxRlliSGkveFF3ZUFDS3MKLS0tIDF3NE5CZ2c1bDVCTXRTZHJVem54
            WjYyY0R6cTBtSCtEUnN5c3JhdnNWUnMKD6KcIhnedvEiJEsT8+mJNiqVgCGUYcLJ
            aiOv31vnuc29QRXXNBewD5kjdGUa4qHdv9/PrKrjicwO0tx/Bhss5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T17:57:02Z"
    mac: ENC[AES256_GCM,data:sQL2sXqhLzYh0gbN5SLDKDOIUBVpxztdTZ1c0olVlvRHEFiu1GeBYp/THAO6SsJvL+wszLz6VdAqjDdSChBstW13nth11XTm45LqHNMfJ+/etTf2pD6pk5MnDc78Kgao3NsIXGz4Dwrzzu06hGRV7gZmmFt45gUj2qjKS2uvBl8=,iv:Hic5U0l95GMQekpNHh2Kl4tZt7HnsBsl+QAOK80gHT0=,tag:r5PsFsoEruZKeX+KfEl+mQ==,type:str]
    version: 3.13.3
