apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
    namespace: monitoring
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:pvadQpLKViFSSmCV0B+YeuwaO51pgtw6kbq5hOak8bdZDODKbI0aNSbARsqv7dfk2zU2dAdZM4YcBTwp2YbK1FrvSbTlPHaSIXheVpvSNSq8pdorALq6RiSRIcBAabisZRGgQzqpYj37sZshxAajCGL1dDL2zZzMXYRpsUitmqk=,iv:Z1nEieQ3+dsRPgX0YzuiQdFpEzX0zWbwHaF1dOhmhTA=,tag:sYFuPg/PkjGsTmSVb/LtcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTmVja1E5V3V0dkxMR2ZG
            WCt4c1B0YktLZWhlUzFVQ0JSNDE2ZTM3M3lRCnF3NU9yWDhWMHJDTUxKaVM0VkFK
            Qmo5M2gyb3ByekVDRzFNYWRjeGpQQ0UKLS0tIHorc0tzTDN5V0xYNkMyalorVDA4
            RUtBeC8vajI5RW5kSEorRHdrWUtmUjQKfLjzxSuLkirQLib5rPXh9o+EeTdowLLr
            StpgWUqB5Zol03crNZx2frcuhMcixowU6dkfkvFr7qCme4FdN2W5GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T01:46:19Z"
    mac: ENC[AES256_GCM,data:it+xx04yIaLfMppXvX/zbxXiPBMhC0gte/3SCB+U2dmjeTYDsXfhRMO/tSKDZATBUGkYYcVM/7UFlvvE8SG2/ZexUDttclbVOzNfmnbmY0GlyK7ipbrF4kNDG4m0ieEvKEYrHuPkxClZmXWoIMS1oYFNVetpsgg+jqsWrVqwwog=,iv:74xTuefl28U+iMJH5YGKqY8caZkfyDsDePzKANyJuq0=,tag:ofRa2bNBMM984LqmdrvulA==,type:str]
    version: 3.13.2
