apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
    namespace: monitoring
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:keVh6eGhauFhN/qey4aPrqEO6f24EJDcHHztzdaZX0HJ1mOZc2ss1fygspGvurvNT+8sJ06cImCscgrlfJ5JihWkYGzcvkvizUs3nY9IbOZAROSoaxHJ379+QfxmSa2RqFW4FeMkn1SIYVWNj2YHmyK0r8/OqPyrZwQEa2oymG0=,iv:Z1nEieQ3+dsRPgX0YzuiQdFpEzX0zWbwHaF1dOhmhTA=,tag:eqG70XnBOUl/UrNz0qusTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQ0g2QlpEMFhSOW5DS1lS
            c3NOanVGTEVjWjl2MkRhL21OckdPcWR1R0JFCmUyUW14eSsyaFB5SE8zUFovQXJ5
            R1REZUtxZTZhV2NsTXV5K2JtT2NVSXcKLS0tIGE3OE5HRzlBdHBkQ01SejdLSnBa
            RzhKQmNJaTRLaHRvTDVOc0pyVytGdVkKP2jxh4PzQEKeqvGcfL24t00WTUa+FXp9
            RV/ZB9+rwHvlS7aG/FJl1ah2W7xtQXO7aJrvrLN6HLUh8NDGnWEfZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qatpp7y6rrl248n739dsnh622jcncx49e4vnrusvdgx0un0t4uqpk40m5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T12:31:22Z"
    mac: ENC[AES256_GCM,data:vACNoRClL3dLzEsSr33gWrXydita8n64NzyPVCCQqUDXQF02PboV/Ide++pg5hLjqzMT9WcuQJcfnccZ2Q1n8gj7L7gVF8JkLXtonQWZurVvlmSegqA4g0+HqryTRtEPR4bv+Wn4araWS91Dwllu6gf0lVJDlBtDJQyYuF8PNpg=,iv:SEMNG4GgmEEOeegckmUZYI6HjeLeOwgqxZ+ntpK6EnE=,tag:mUixPoaS7DxGXu+OoHxriA==,type:str]
    version: 3.13.2
