services:
  jellyseerr:
    image: ghcr.io/seerr-team/seerr:v3.1.0
    init: true
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=America/Toronto
    volumes:
      - ~/persistent/jellyseerr/config:/app/config
    expose:
      - "5055"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    networks:
      - home-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  home-server:
    external: true