apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - deployment.yaml
  - metrics.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: kea-dhcp4-config
    namespace: network-services
    files:
      - kea-dhcp4.conf
      - iot-reservations.json
