apiVersion: v1
kind: Service
metadata: {name: jellyfin, namespace: media}
spec:
  selector: {app.kubernetes.io/name: jellyfin}
  ports:
    - {name: http, port: 8096, targetPort: http}
---
apiVersion: v1
kind: Service
metadata: {name: jellyfin-access, namespace: media}
spec:
  selector: {app.kubernetes.io/name: jellyfin}
  ports:
    - {name: http, port: 80, targetPort: access-http}
