apiVersion: v1
kind: Secret
metadata:
    name: loggifly-secrets
    namespace: monitoring
type: Opaque
data:
    telegram-bot-token: ENC[AES256_GCM,data:7Efmkm5kG57RNEmWYLBserJxumWHEKq3OZCB1YeMuemzc61UAiBfx1BYylmrVhC7N2MpWp8eYXcl69FaMEDJlQ==,iv:bNzDrSLC9NZJi/aOP/IAEqAOsQ3diPAd0LY0QCwj5SM=,tag:9qCd6s4orVquu8jrGh6uYg==,type:str]
    telegram-chat-id: ENC[AES256_GCM,data:Z1M//rLUURy6JD1h4BjwaaaBC8c=,iv:FrOjg6VPU3LgBGixImTdf+QTQbTBgsgpJ6WkyGVzv4E=,tag:3zwS9a5VPx5TSgbxAkXh8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2T1VpaHhXOUY1UkdwWW9Y
            aTZOTjlyTW1FZHlSQkdJWmk4UnNiMnhkdmpVCkN0TVE5VXZyOUJ6WXdhOWZwc3Y2
            T2JSYnlkSHA1TGhoMngwWEJQTUZFSHcKLS0tIGNUSWRXMC9LSmVmMUMyWGplZkxm
            bzVhVFZBNXh3M1J0TzNEanZwYUJjSE0KK8ccXKihNWwgqEwGzKEDd2Yw1OzS81/L
            M4YJaKi/gI5lEINgwf5r0uwVucZYQ4gTbymCmYMWhasXLj82nJVyqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T01:46:20Z"
    mac: ENC[AES256_GCM,data:7fITUQWK6ymuzfpKU5FPYsLPEgHlJFJYlDzc1nJNQkfBPzSM+MRh97u+1x1mAphBT7zionb9jMmdR9eugH3XD/IwebBirCEXx5tN+BDCNjbOF+mB/8SshCXVTnr8gd8NGtNPbpX3D1n5Uk1TtRe9gyfVaouUENE6O/R7DPgY3CY=,iv:uhEkaaF/wpnwbx7Pox/80cZqmD0dJvIrrFuNUBYwr/k=,tag:Mqru/dWU8k3/Yb3A9Fz4aA==,type:str]
    version: 3.13.2
