apiVersion: v1
kind: Secret
metadata:
    name: loggifly-secrets
    namespace: monitoring
type: Opaque
data:
    telegram-bot-token: ENC[AES256_GCM,data:XCuIHUbAuC//MZfnJifvsMp/MDNq3+Dv3ONZgI3AuFH8v9CKK/NqXxMVFWUx8+o4/f+iktomOzu/MNDmCEveFQ==,iv:bNzDrSLC9NZJi/aOP/IAEqAOsQ3diPAd0LY0QCwj5SM=,tag:xep3dDosewxEwpm3gTUetA==,type:str]
    telegram-chat-id: ENC[AES256_GCM,data:+ovDJTJ/g6f0gvfh6IXCsuHC5fI=,iv:FrOjg6VPU3LgBGixImTdf+QTQbTBgsgpJ6WkyGVzv4E=,tag:OHALXYDb6SnVTb3jyDqazA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRTUwaGJWRGFwTlZyeUsz
            aEpUOXFSN3JsWjBYMndKY2J4WHZTVTNyT2wwCktTK2Z3V0NITENTQmJzMHFOOW91
            bDNOVHJkbWV2SlNrK3NPMExXd3RLSzgKLS0tIGs3M2IrcmF3ZFcxa1BIVXJ4QWdP
            WTlVYTZHWDBXdGlnOFBVQmZ5TzlPemcKqhERl3g4Dlqz8dZJqj8P6Vqz543ddPfl
            IjgQ50u0oy+kqdHkfwQ18BRxdCJ3c3M5YMzXLlvp8+FccZzr9TWQkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qatpp7y6rrl248n739dsnh622jcncx49e4vnrusvdgx0un0t4uqpk40m5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T03:32:15Z"
    mac: ENC[AES256_GCM,data:bGMj0VYbKHVzUZp42htLY1EJLKwjSWEmiPNb9K2PI0avN3uQVrkUBGlH0YqbXudcsrhHrnFsKZowRoX25EFojlacVJA8UcO2SAQpIeIwCM6zKRtFCahu2+s1sGk3dV8Oek9Ao9w4ZeMW1lTQgAM2Xt/9hD+iUlLXrmjs8/9ORic=,iv:dWX4M09H+R9wk6RQocpgBIh20MHjPegJn4SdRPuCPlk=,tag:aXGxybrdPuy5fykHaGZkGQ==,type:str]
    version: 3.13.2
