apiVersion: v1
kind: Service
metadata:
  name: loggifly
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loggifly
spec:
  selector: {app.kubernetes.io/name: loggifly}
  ports:
    - {name: metrics, port: 2112, targetPort: metrics}
