apiVersion: v1
kind: Secret
metadata:
    name: observability-alertmanager
    namespace: monitoring
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:GS0g+XUHHuYw2qBinHHUTToKy7gQ1n4l5ODhasnftPdFcNzZhPm8wer4FXDU2pi16XJQ0flNM7USlzdUDrvyGQfPxdDd3hH9Rh5vTjVYFuYEVb+oCCGSApkT8LMcKb7YZQI6VQmQy1omeZYOFpj/saTeJkfYyUThkTuIhL0oVpwKMBaB8P1KPLU+9hnTZKy6/NMl/ui0Amd8wO50ehdSoS7GFGz9etKfut/uWGMmuCgzNXkgeoiRrDCYdKBicrPAuyvdzm95ZN23lxG8eu7T6it8LZyygsrKKXPs0OsePXi3HdwyRaoTF8mc+yH90ONNlrK9aCYB6+ONpgaLXT67VW6zuwp76v2omnkGXV4vXTTzeE6WwbhuT31AaEZkTzFiw89JSSTdG9FlMgsUyMpBZDQguYH5r47ZPC5T5b/I495xYjDp/t8ErRl7RwmTHO1+Mopzz8lI3PAWmKlmxwsiJqaVR4TjebAXpE5VWZ2/dsTtVIhgvVPj/a4IrP0bdabFJHqoOztOcsgHfUkbL+lH//XbMhv+diqnnYZegdRqqlnvTjv8X2TpFEhBEeLhpnzugWvPEi0c3SocKSfXcB53gVUvVchEoo8+h7gUyp0WhBpMA6rLFZFoilXQSW2s+F3mKZqDV/GOcXidJcV/6Cm7Rtszu18WKiREbmvafo42XiXumgyiKTMJ6MmFy7GQ259vYrIkLFs9VQK6BmezCr+Z7Kr1uv9pDAdlBiTWFEc4M1GtQs5USmAs8xgHuBBhoHwDWLyF8Pw2GXSy5m8iy19Mue1K/fn0FiVxtmp6DDKvhJDe4w4Y16OPX/F+PQMnSOc8H4iPXSN+lcFPTCGwISQD1jppMEvEbpOv6McGRHrFuXxBoZi2Q3wHvBMLg0T3JxZQQ99TFCc6q9/r7e2zUaQf6ooOYp81aNROG2Zg3o0GzFTCF14VDLp60yUcLuypjNQ3iXP46EEEOYqDSKyrL1FlWb0qSYCuiUyr2v7q+ZiIeZXE0fvPEjHXCmJ/4EvoFVwt/OMtHpfPtDrTZxQdgmOFeVH2t1I4oxqzDMiUg//Ruvo2bbRS8myo+SqFdYS+fPW12KhhOEWsb1lGRAyPLZ8Dh+iUTFmSECscna5HDapNk5iyKNUHVRZrE948aQF8AJI265/Yzj1dJW5pIAM=,iv:dVNqRqhCzag+/8zNK8veBAm4Kx6t6kmxeOYKMVgyzpU=,tag:7RIj3HARWv7wlkuUXAdy+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNmFlVWNERHN6RWNTVXln
            akN5MkZuZlk4cWNQbkpuSjRsUWVqR3NiUUVFClNIdDR5ZmUrUXlNVEhXN1U3R3Br
            MTNHdnMrR1JOYzJuOWRVT0NjNjJGMDgKLS0tIDRPQmNGR1VvTnZteHoyYS8zY05L
            dkFCalNpUU0zQVh2Z09LZmExa0lEMW8KDr+lqImjsCHuz2yJHj32UicTPHoOs0Lr
            I7uf4CeRTK+nHBhiLvwXZ+Jy0DWjcjin0MUxcrReHxsdqD9hmUxfKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T15:13:47Z"
    mac: ENC[AES256_GCM,data:FSA0EAZbyYtkyncvgWQ1j4NyK5X1iICdkigwyrtBQlD1Qxv7+u7p/SnDCUtlDhYlK5qdxGlOAPSznMys3Mchdujgt4H+AqzHe7OHY68XeKp3aoI5YS75SGeOc+bT1kOkg/w6iXEjrKi9FX+rq/92Xkdfqmz5b4sFI81R39ZoYZI=,iv:Hy9owEcBpt7iCqH+HUciwl899tnGGbuH0LHJxQyEzjk=,tag:qovo6lQPgrQz0ciPD36rJw==,type:str]
    version: 3.13.2
