apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:lkvP6w==,iv:1liEVQ99pyheYf2Q0FeElvaWBuz6hnvu4xCel4zqIAQ=,tag:dv9Nt0ZXOpKdJVBybtvHIQ==,type:str]
    admin-password: ENC[AES256_GCM,data:4vsvh/0mEmqONFVSD3GOkljbUyNGKLtd6QpcXtJWaIKCtcfW/rp+eYlUI/l5bsMI,iv:shSzqpphYLhVNKwLldj41lpGA9ujB22bLgfZQ2E/+sA=,tag:cRdv+f5/gyKCVuoX1EywOw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:/C+Jw6T9pw==,iv:vVA/0qTbTzBf73gX0nRgf3Ye6QhkZH917VtzG7bgYOk=,tag:H8XNOkbdh3pGfS3tHnVFRg==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:aYMMIMjQVVn2h7WxnP9Y74H2H0U8bzRJ6sRbgGUOvcEBISzIb4juo7M81H2fbVkkFlUjxqn/EkLO4GVcw5txSQ==,iv:xM7c9L9Yruggi5x7bh7+4YhLtG/dWASRZpzD6KQI/yY=,tag:E3DV41yoo9KedD8m33m7qg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbXNjQTFVTi9ERTVVenRN
            MWRReFpZdkMxMWhPWk1yZ2tBM21zd3EvYWp3CkZZMXdGdTRGR3NhU2MwUFoyY0RO
            QzVnRFZibTlYRE9CTGJUSmhxUE9MeE0KLS0tIDlnTG9kMlprU1Q2L3AzSEU5Zy9J
            UjU2QkZ3Ym8wd0NYR2EzOENsRTBhTGcKtrC2xufNpQb7sRFgPkIsajgSeQaEcFuk
            U78gfk86dsv/wN3wo23Nxvj927/7j1epV0rGQkj4eXRy0VzM+BE+zw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-16T14:41:59Z"
    mac: ENC[AES256_GCM,data:uLtEr49WeUpps3+5VCWeYaL7bJdYkGXfGSmUGhEU5nTPH23bZOXp7FvReu7+Kmrqdc25LY0vfiQ/GwZHnWO/QVXO84xzgABoI0YmtxPvKnlMaRoGtxMGDYay4uIX2Zd4GnYtIw2Ytk1ZiKn6stQxG4rJpTl8WcKU4CVoUIvHkZo=,iv:aLDm+rn/EpR0eYWL8LGfE2sZ2WdDAnRgJNkTr9/Wf30=,tag:wEvcWycFe8k3ttZi0S+Nag==,type:str]
    version: 3.13.2
