apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source.yaml
  - storage-class.yaml
  - grafana-access-proxy.yaml
  - grafana-secrets.sops.yaml
  - alertmanager-config.sops.yaml
  - dashboard.yaml
  - network-services-dashboard.yaml
  - backup-dashboard.yaml
  - media-storage-dashboard.yaml
  - ai-services-dashboard.yaml
  - media-storage-exporter.yaml
  - backup-health-rules.yaml
  - rbac.yaml
  - release.yaml
  - networkpolicy.yaml
  - route.yaml
