apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 12h
  timeout: 2m
  url: https://github.com/longhorn/longhorn.git
  ref:
    tag: v1.12.0
    commit: d5d522b70cbd134e35e424fea9812d1c117fd8cf
  ignore: |
    /*
    !/chart/
