apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: juicefs-system
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: juicefs-postgresql
  namespace: juicefs-system
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: juicefs-postgresql
      app.kubernetes.io/component: metadata
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values: [juicefs-csi-driver, juicefs-mount]
      ports:
        - {port: 5432, protocol: TCP}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - {port: 9187, protocol: TCP}
