apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: juicefs-csi-driver
  namespace: flux-system
spec:
  interval: 12h
  timeout: 2m
  url: https://github.com/juicedata/charts.git
  ref:
    tag: helm-chart-juicefs-csi-driver-0.32.0
    commit: 63177df61c7a7f1b8f9397d9484397e2d73afae1
  ignore: |
    /*
    !/charts/
    !/charts/juicefs-csi-driver/
