apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: juicefs-csi-driver
  namespace: flux-system
spec:
  interval: 12h
  timeout: 2m
  url: https://github.com/juicedata/charts.git
  ref:
    tag: helm-chart-juicefs-csi-driver-0.32.2
    commit: 92667f92367d50a967aa72d1532aec6587e99178
  ignore: |
    /*
    !/charts/
    !/charts/juicefs-csi-driver/
