apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: calibre-web-config, namespace: media}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests: {storage: 5Gi}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: calibre-web-ingest-rwx, namespace: media}
spec:
  accessModes: [ReadWriteMany]
  storageClassName: longhorn
  resources:
    requests: {storage: 20Gi}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: {name: shelfmark-config, namespace: media}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests: {storage: 2Gi}
