apiVersion: v1
kind: Service
metadata: {name: calibre-web, namespace: media}
spec:
  selector: {app.kubernetes.io/name: calibre-web}
  ports:
    - {name: http, port: 8083, targetPort: http}
---
apiVersion: v1
kind: Service
metadata: {name: shelfmark, namespace: media}
spec:
  selector: {app.kubernetes.io/name: media-vpn}
  ports:
    - {name: http, port: 8084, targetPort: shelfmark}
---
apiVersion: v1
kind: Service
metadata: {name: shelfmark-access, namespace: media}
spec:
  selector: {app.kubernetes.io/name: media-vpn}
  ports:
    - {name: http, port: 80, targetPort: sh-access}
