apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: monitoring-to-authentik
  namespace: apps
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: monitoring
  to:
    - group: ""
      kind: Service
      name: authentik-headlamp-outpost
