apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.sops.yaml
  - oidc-client-secrets.sops.yaml
  - application-blueprints.yaml
  - pvc.yaml
  - workloads.yaml
  - services.yaml
  - networkpolicy.yaml
  - route.yaml
patches:
  - path: generated-oidc-worker-env.yaml
