apiVersion: v1
kind: Secret
metadata:
    name: authentik-oidc-client-secrets
    namespace: apps
type: Opaque
stringData:
    AUTHENTIK_OIDC_ACTUAL_BUDGET_CLIENT_SECRET: ENC[AES256_GCM,data:sZIbLFakMtgAkcI8iChq3lo2779M6piecscH4zxs9O6ReGHN4zAVn4YwDu/ZlLkgo9WIk8wU1amMg72LGfxwCA==,iv:YbyiEzCYHlA4nMZeG88HWKGC6qRG6mHe3YhMgqSo9U4=,tag:LKkbNGOFvpp1KKW/kT7+cQ==,type:str]
    AUTHENTIK_OIDC_OPEN_WEBUI_CLIENT_SECRET: ENC[AES256_GCM,data:oiyL5CxHPSfju3Je695xgydZh9N+PtSSVNsi9Zi/GkQ8NAfmpU/jBOe9TeQxQ0B40CdGkfLZ+DZ0ht1dkH6K+g==,iv:F5erh3+H3csO/XfGHLk8P/rIIitGpz+uAGrM5HiEOHY=,tag:4pYg3Yh50EXkFq8IPgFadw==,type:str]
    AUTHENTIK_OIDC_HEADLAMP_CLIENT_SECRET: ENC[AES256_GCM,data:u8BVEjpxp4vxbzfiln0tI7IWEdBeZ/cJ/B+v2G9IjnGJ07n/wMpQuFIsrb/Gf51+w/KlB/EPAswjCJJzUUEWHb5wFJsB5BKQ6kRta2RW7zw1fcWG1uwdReSAVRXDSCFljQgEXlDp6zkvufJ2JLZXFBOMbMGt0Pq6ir9JnGSfuQI=,iv:Bwe56a/goXYAY65pYDVn9ZOJjT8EUHGlelTXPeV3VWU=,tag:wbPFh7AwbootoX/lAiZ13g==,type:str]
    AUTHENTIK_OIDC_AUDIOBOOKSHELF_CLIENT_SECRET: ENC[AES256_GCM,data:UaiH1SlYYdAP9uMQ4CZ4J87xY57NoMa8pL4A9ZCmBEErP0PsZrvFYdULOC/mW4CxU4hTiVdlavADCeY41Tqss1b9xlQpkXjCn2yWCkPE8EMwtzLUvPK7L1pzYZVqZSqY,iv:1PuQby28T1pwKajJulve8FxGEgOdtj1FFrD6cskh5s8=,tag:ibTSW+Vuc9FG/W7NKZsCxA==,type:str]
    AUTHENTIK_OIDC_GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:4G6aRBAgP12ELCvRfSKYN5pP5nP5qrJMJfmW/ZtW4R49SzGlw3QKt9U3lavJsyCKPVs8U4/jxIGUKHkMwR3uYw==,iv:MuD3US0cD5Ik2HDDhf52eruVairqiu+6keVF7NH8aTg=,tag:jArlseecgBrowxTq0fb77w==,type:str]
    AUTHENTIK_OIDC_VIKUNJA_CLIENT_SECRET: ENC[AES256_GCM,data:4yqBV68nM6Ab69zgoym1TH+Md3Y1AhB57z/KBXcno99w+SsRP2l65FmXWjCQZzBsG/0rnHGivJIhgFgG3kC8sg==,iv:WwqUXl1C7zYO71YD4V/YmE3LOtyY1zvf6x2A25dvn8A=,tag:XpEjKHPHdJVPY2JJl9PoGg==,type:str]
    AUTHENTIK_OIDC_MCPHUB_CLIENT_SECRET: ENC[AES256_GCM,data:fKRm3eEiFNKPVWqLHigQTG1IA1gUy3wYje79tZknMuEo+u/Tg6Oz4adqywQrzDMPsuGQuISourYelo/qzv7rNA==,iv:VAtiqInljQR1iO8FUK4MnZmGEibonO/x8EGQUeAuKfU=,tag:l5jo2ltIC+xJGzD0pdXe6Q==,type:str]
    AUTHENTIK_OIDC_OMNIFIN_CLIENT_SECRET: ENC[AES256_GCM,data:AKh+JIQBGJHRoAbeV/sC+7SjGs2VwlcEgz+bmNbKhHVlQ3PRxeVr3Co7hjci2DpkL7Vsi6h6VomK9dagOjzdmA==,iv:5Q6sI9nEvXmpFlXIcq3ACCiZ7KVHllUTuMty2etJGGo=,tag:y2Azbv+54t6TywAvcoeVuA==,type:str]
    AUTHENTIK_OIDC_LLM_GATEWAY_CLIENT_SECRET: ENC[AES256_GCM,data:8wK8yTUA8r9XJXWpFqU8dxDem467JV8yMIEySkWG2TnITAujmSTkZbtFV3qihoYiC2U=,iv:emi+YrKK853s6dyPI2oU0ITjnd82TcZJ0tHl5uhhzWU=,tag:q07a79IA2WZ3+bKYcnZiwg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTkZaQmVmWHhDMG9XU3hD
            WVkxWW9qaFE5S2w3bFh2S3FqWmg4aFZrUWpVCkZaa3FPdWRVY001eXppSU1ndU9l
            ME5uVlc1RlFJR0tCQWk4Wk8xc01UYTAKLS0tIDJ6MEs5eHBaMWw4QmJrYml1eG9B
            b3pUbnY5dUtDcmsyaUhLUktmcnVqSlUKGhcc+VPhBtIJRjAf5HyOoRvgKyvXEjB8
            D1H9p0XFdoznpOpAfEU0+cpLR1gOLYejUqcstmDmJ1BrY9YjrtXARQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T19:19:12Z"
    mac: ENC[AES256_GCM,data:/tU3T+wBcUa8x/kCsLjsLYyjAaZ3aTOc4Fp2W1QJAemibf51OAmiUVh2A921ZKeRsMXCs3OunyMEwe7UTZJEZrIxTGe6CAHi3nBdXCuhUX7oN1uEO1LikfVY9aYkUUQlTupfv7nsAVJPlKsSZGiFCFl1kA0uD6HNnvmOYkqUucM=,iv:EhK7c1neKH2ZL/3ZFMczmBfJZ3x2hP+qUESw4w3iGMU=,tag:E8X3evWP1cU9s++1nbWSNg==,type:str]
    version: 3.13.3
