apiVersion: v1
kind: Secret
metadata:
    name: authentik-oidc-client-secrets
    namespace: apps
type: Opaque
stringData:
    AUTHENTIK_OIDC_ACTUAL_BUDGET_CLIENT_SECRET: ENC[AES256_GCM,data:D0YhZbta2dOzikA4+/XmeQ5Y8HKoQyJ2aqDnT0kMEljnMshBRSPSX8F3m+YNzO5ZP4LmRnrLtkzGbZyWxa2wpw==,iv:yJgPecuQdU/hcz8Vbb3P8HUAWOZ8CIUVvY50WHzW4OU=,tag:Wh7d1qY/P8FA+gk4z75uEw==,type:str]
    AUTHENTIK_OIDC_OPEN_WEBUI_CLIENT_SECRET: ENC[AES256_GCM,data:NMl+dHQobL4zxBr/BPM5Z71hScixVUTlX9C9LDUPJpkDSX2XTuwd7K3iL8Nwn821VrWytKOtA5rAJU+3TlPchw==,iv:2ASiL3m+27noi0ZQriO9R71XuqJd5x31BQevpXbLFyQ=,tag:DWoijs2DDp++NeStaNROdw==,type:str]
    AUTHENTIK_OIDC_HEADLAMP_CLIENT_SECRET: ENC[AES256_GCM,data:/6BL7LCP354LI2ALjm5P0A1PMbg0o8CuFr9eCTF6VIrluQ47ws8g4egNR0NPuRtnf4Fxn5qyfhCQBOkx7I9C6q0+6At7kiYCT1fUVlUe5dBPAZ3E90N0cO0mgb+sGi4eOC/c1K/tw54Fot5nESOxpxbMSuYtJyrnW2CULuuBUyo=,iv:kz5ExRetNP9UkZgaNloUEoxLCH6UlxTDY+7vNk9u+Wc=,tag:MblJAjzQo9iXau3GwSoCcw==,type:str]
    AUTHENTIK_OIDC_AUDIOBOOKSHELF_CLIENT_SECRET: ENC[AES256_GCM,data:om4Hl0bgngI/iPR8CxYyVT5sYqpQl/WkUpyBVL/Xy2AwxRU42OjIo0+QO3xsGPGzY5oTOCG3INM/8lX14Sj48tI5WTfig+UeDShQhmuD+VGtVpMlRIIGydE20lcFPxaE,iv:nI3r8IgqMHORxSAxn5JM6kr8Ti8MIF1vf7NXZ/w7hSM=,tag:/0bxJB2MrCkFMJu7c/ityA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VFNGd3U3WUgrSnEweHA4
            SFNwUUtsN0F2TThaeEgvT0pEa1oxd1V1dXhzCnNpcnpMejhidHFrWTUyWmpSUjBS
            QkN3a0RqdFBIalVlcXQvTmRpcWppQVkKLS0tIEl5ZzFEeUtTY3lTU0F3TTdFdlhk
            UDBpZ0h2U2d5a2xrL3NvWisrWmNnOWcKdUUFqA+22KAf86DFP8TuWpZGe1QFpvKh
            4mxoP/0xsSFXNz7XqHs6HszHWixV3HXk8ratwBxq2wDXHO3cyUbLKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T11:44:48Z"
    mac: ENC[AES256_GCM,data:ApMu8xuM9XAf7R22A/S65HLctw9dMjVRQdv6JUlVKODHfFouJhWgT33/G8IldQsZJnBmPoG7GPRJNg/UBgvOAodlrC5biPM8VEOTsrpjyV8HEmFUkJDZNSpxtcxp2JG0tu/QbsnlCFiqJhmgW+ynGU7pcyxfDa5VrTUfVzPvLO8=,iv:tHX7dsnw6IpfFA6kItdgKTesFeyoHYDKE2upJ1zGg0s=,tag:glwTUYvZKKx2obFpNlbTWA==,type:str]
    version: 3.13.2
