apiVersion: v1
kind: Secret
metadata:
    name: authentik-oidc-client-secrets
    namespace: apps
type: Opaque
stringData:
    AUTHENTIK_OIDC_ACTUAL_BUDGET_CLIENT_SECRET: ENC[AES256_GCM,data:SXK72v0U3TI33/sdin4nnt20PMh6g5y0pxtJdwC0vMEbZUStY/bqO42OUxGL4E2jjhc99cek0Q063NoBY6xTWA==,iv:KClQEtnTufqbSlZWdvuH0GU2WEWbU7BlSfrElR+k7dQ=,tag:VfQFx2+g9Ywsw6aOwxzFnQ==,type:str]
    AUTHENTIK_OIDC_OPEN_WEBUI_CLIENT_SECRET: ENC[AES256_GCM,data:RKJcBtflp7awDPP5QjM21XGbGVANJvnQK7XveSyyqG7fzpg58LIusp7hvV3WhG5Dq04ZGohkLYkl/MVWvwFcLg==,iv:WfzqrF1ayiQctemRlHAP1WX/+4yRHURHLNS3/jBxxHc=,tag:X8RiRYJeK3jEJy4EnUGL6w==,type:str]
    AUTHENTIK_OIDC_HEADLAMP_CLIENT_SECRET: ENC[AES256_GCM,data:iF8nMKp8AEISydEp3LldWGKsw25W/ckgCOAVpqwdBkAk67zh20/9zwYHqqEKnwMt6hbvlqDudIC3XnEIV97f77Q3yt9hskTUiXCZUC+Fjw+oS2/KLTc0OBpV0m0R+OyvvQtAcKT4I4AD9v5hL9K4zRfqBmTGormR1ettBVV0fss=,iv:/f8h2LQxSXpfRG3IKZPjs+q4UFMABvZwcL05McKFGAk=,tag:V7YbTN4bV7nVrlqyo9i8Mw==,type:str]
    AUTHENTIK_OIDC_AUDIOBOOKSHELF_CLIENT_SECRET: ENC[AES256_GCM,data:3RjkbMe24cV0mwo7LBy8fo8Nl19nqspKWuy88YDkNf/KFxYx8PUbfWegkRaTJ2cflQakletGsy1q4lCbkawYtbEiTeyTLecJWm4IKoVc/3Ax5fp/EiP4eWzqCG6NvwdT,iv:7Sw/+C9RrfZdplBv5jl92yoV2NMWOlWjjFU9Wu2UjgA=,tag:1XGmJK/Kr2BToKgQaO5+YA==,type:str]
    AUTHENTIK_OIDC_GRAFANA_CLIENT_SECRET: ENC[AES256_GCM,data:2c3AylUuh95OPxlnwkSuOcm9tQ6SWcPub2cl7G/iTRJa39/Y/cDEp/ZiUyKj0i3McpfCHlzdutYaM/1DiK/CYg==,iv:MGDGXygp1qraOiB2oB07NLCuwHSuIwCMn8b2Iki2mpM=,tag:biCApRa/nD+tLabishokyg==,type:str]
    AUTHENTIK_OIDC_VIKUNJA_CLIENT_SECRET: ENC[AES256_GCM,data:sEgGISGr5jSBuykm+XANTR30su2QLUAWsOCS6e5lBgSUQqyCDMj5DKjMNpDK87Fha7tj2aiHCoPd7V/u/aYEAQ==,iv:cpRuqUFdgH0ZiBzuZlKKxL4gmCnsnlWlhLvT06tvI2Q=,tag:s404u2PBYU0wcj+/jW96RQ==,type:str]
    AUTHENTIK_OIDC_MCPHUB_CLIENT_SECRET: ENC[AES256_GCM,data:3vDeo/OzP8kwmX2x1iyrM5I/r0DDwo8MhYz5eTSF8DbRv4766v+jqzS6yuei3Fyk5p67WoTIrZGf81Wux2aI4A==,iv:FKK+BLYY2eJBfHjb8J98peqXI6VciCaq2y/T/twGcPc=,tag:Ad1Qv5KUtAF+S13UzgE8nQ==,type:str]
    AUTHENTIK_OIDC_OMNIFIN_CLIENT_SECRET: ENC[AES256_GCM,data:Rt/KubLuJc/XqXa2PWKwIDc6krvm0dQgyf9YaXyyLILvxndnknWXU4pxnP4TtuMgCF0g9TKpa487JdELhdmnZQ==,iv:bTdYY7qSBEH2A8ryaxYJxfHH27x+BQXnuN/gBLP1MQo=,tag:Ferslz6Mt7xnTOmpm+/nZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Rm1TUmpBTkR5NEgvM3U3
            YlhwdDhNUjFXc2xpWXBWVnZLTHBZSGp6MVE4CldpbVVuNGZsTk5LV2RqQ3FSUWpZ
            U0ZpT3FqVmQxNDdudEtVbnF6aTM5RDQKLS0tIGViK3Y5U2dFMmFoZG1DbTE5VmZm
            Y3dUVVhSVm9NaFgwRUlsYnkvVGNzOFkKtG9S9jUjsTrhIDJJQEeQiDmNi0N/g1qv
            QPBCBV9TGxZjecPBNxJJxPKy5ifHQ+rrx7d4obgxK69Q2DvgTfyvEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T21:07:38Z"
    mac: ENC[AES256_GCM,data:FUt/tm0Fo5LcBEDgjpcwKTtGsdmSqdIjjo3Op8c+m6tcCS1LYCajTMwc4Ux2c+JOouClpzgoiPoKHpTR2daNJWfTsgPZoJjV2NfL1BPzWJeLKB0gwO8Ds65nAitcGpwN4LSYDI5w5X1csjK2OgBEJVmqkI6cNThIGuI749eBjVk=,iv:Pxb+nxvoA4sG45f0X9MF0Kv/kqheYrO2+wxIrqb793Q=,tag:8ErIc13oWdNNBYYCnw5xuQ==,type:str]
    version: 3.13.3
