apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: apps
type: Opaque
data:
    secret-key: ENC[AES256_GCM,data:9QJ1H1QAZOenajkxVWM6sEAuzaw+eaoaVvHFIJsej3U9et3UO3aJOlXAsz2a8mtRjNFW29tpe8FOaoO8Efm+NaHVFOU+aljLHKDo1rvRwRTmtnMWvETkwT1u5Rnm0A0R83KpvOMdUaBc88mA,iv:Y//LfKmwW0laaPwP/li/ufk3vW975h9NRq9BjwX3oV0=,tag:R2p6EMbnp9pM/pCelGIK/g==,type:str]
    postgres-password: ENC[AES256_GCM,data:PPIJZ48ezhCPLjAdfi8/UVTZfrowRflw27WdHJr/b8LE00/UbOyL4HTBInpZp/HUM4QPfP47xoha3uXiiKf0Ji21dGY=,iv:IARTl4bafPid0UV3kC2jnz22ifz9xHFNZ8OyV1+mDA8=,tag:FQmnVmtcx7sbH9m9npe/GQ==,type:str]
    bootstrap-password-hash: ENC[AES256_GCM,data:1kIEE68P3GHNieR2MxCwpPLOVAZMgjbDBiShWGbZxvG75Ck3v832PaejoLzXJ9NXlgQITXyUWPSxqsR/UtrixsOS2f29pIdeYpFKSsCzAvPy477Ufdj7LNltQ+l4D7ebjdV/YQs4xv4ZOeBuax6+4fSWunT1ep/C,iv:lRho7AqlYXBXA6NaNPdzRj6s9diKCoLa2XCod8wlq+Y=,tag:GIiPggtUEav2rUxdaz7LkQ==,type:str]
    bootstrap-email: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUS3lLR1ZUR1MrVWEyNmN2
            WjhMcTZHekM2eDhUcDJzUXo4dmFFMEV0dUNBCnkrT0lJZmdLVFBYZjdldDhmSU9W
            Qms1bm5DQ2NOOEJlRnVDY3RPSzdaMHMKLS0tIDBTYU9oa1FFVGE1L05SWnZqRzlm
            L2p1NmlLdndKbWtsMVpvOUJVODk5Z1kK5Cr9GZ6LYsS5fMLreEE14Hg8Uat1j29M
            2zgT/ZMQGegkj2tClm3Q6+9oqxJ1MVTTlvls5YQz4j8ofXvNigNtJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qatpp7y6rrl248n739dsnh622jcncx49e4vnrusvdgx0un0t4uqpk40m5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T00:25:45Z"
    mac: ENC[AES256_GCM,data:pZ+iZKGO7oNQIuluMTZbKfqdOnsRyh+MhYisA0Dhq4yLmYo1lK/4ddfbNq68uLmjaRerSrtXv8x0TYxOQpbGfgo5UN8iAAuu1Hi6K4w/8AfqVkl3ZeMSsYqYghz31WPO91DJ6dGst06egEdLUtrfTEgUIgi4HTlmAzchF/NbLsA=,iv:0xuLzqRFo4q8+5/2kN1lmNmskQz61Ut9mEjw3DdqcK8=,tag:Z7lw7eQKoZ5XMvQWt/W15A==,type:str]
    version: 3.13.2
