apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: apps
type: Opaque
data:
    secret-key: ENC[AES256_GCM,data:KxBwd9vwkY26qWLaP7kWJ24E82oou2DXQvGoL3XSBTcScx6ks53ezPNi8F9QKbQx/fKAj7wiK9sIKbMLzoX17A0osYH7VYBQf/C9a0BuIfr35A6npofjKPTuiPHKwVhZBX894DXN7/VC8H3F,iv:Y//LfKmwW0laaPwP/li/ufk3vW975h9NRq9BjwX3oV0=,tag:BbPAQGfXzw1F6ZSEszi+Mg==,type:str]
    postgres-password: ENC[AES256_GCM,data:B10ihcWT58ZP0+faukFXie45+iTLa0STfe+HsMWCJ64/t/P7SU+psrikiVMaKJvh2FGX5dVcf2HIDkpDFSvp5sLQmxo=,iv:IARTl4bafPid0UV3kC2jnz22ifz9xHFNZ8OyV1+mDA8=,tag:dZ/3302jZ7aFWfQoGD6qXA==,type:str]
    bootstrap-password-hash: ENC[AES256_GCM,data:hBOWujHjKLPu9a8JZrcvddB/3lHrKdLE88uKOpqr1BTka82Qz8IRWHAtkAqAcEhT4giXiy707Wl33wqfUW+ANpGCftuV2BjP066JpARWHv5bL340PUePutJjaJEes15vfSqTGoAHRZwG92q/8cIaVCfIFE6if/fr,iv:lRho7AqlYXBXA6NaNPdzRj6s9diKCoLa2XCod8wlq+Y=,tag:52Uylp/HaAkJCX0n5i3Hbg==,type:str]
    bootstrap-email: null
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRUhnd3Bsc1hRd3gzOEIy
            Vm5TRzc2UTE4TEd1Nm1jWkR3ZUFHZm5id0dVCkdTTFRyZFkwcHBLMDRHMlhQTUlT
            enBpb1VKYlZwR1RBYlZCNFFSYW5rUU0KLS0tIGZScmdMUFVIV0M1TUxSRko2d011
            aWgrR1JqaXArZ09UWVhnclhFRmlwNjQK+CLUDydnQ4SjsPuG/bJ7q9509uckFCe3
            /3vrgJoduOAhtjIlv9MFqvb01DppVEsqdPPXXAX44+5mlvjQvH8n4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T01:46:14Z"
    mac: ENC[AES256_GCM,data:l1sz+GCvXxH6QYZ4weMJT4qTsro2llBx60BtEioskHN0ETUyt/5lhuirDb7KNW1CcohfTozkIkLJp8TfEi5O3poFa1DCo1a+0Ra1mNoZa3KZc6llm2uXeQ3knjVgLf2gz8RxktoPs8YP+IYbAW+g7xn1Xz1jLkzd2oBfcaCFmMo=,iv:5xnbwbY2EfSGbwegO1KS2fomDLZgoDSlfnfh9AmZl24=,tag:kNm5e5LGt1td+7/j/pOY4Q==,type:str]
    version: 3.13.2
