apiVersion: v1
kind: Secret
metadata:
    name: actual-budget-secrets
    namespace: apps
type: Opaque
data:
    openid-client-id: ENC[AES256_GCM,data:ngjQlHG+TQIc1puHcfhoB0oI9G4Wmrx1SYlCqYPNvhsHWk/R4PFNlokqZRduqDen92+SPg==,iv:8Nzvqc18Ra0LgRDXu1KLrtq3l+fSXrTCrDnfw12rlPM=,tag:YHX60aPFg1wBJ0LKqwaeBg==,type:str]
    openid-client-secret: ENC[AES256_GCM,data:mZKwzzA0St5QfPDQYOJp1xG+RWBknNJgRhAImpCV8WZpExW0JmZvzBoRt+/d//JvAGnyN3TEfHdZqfCyDu6eNQuGbQsSF9bnWHn3K32E/syC9xKfv3zcpA==,iv:OmdpYlCV/AVXVBk6szUUhdulXhM6qBXucolaZTGr1gM=,tag:pXfjGalgPmkfdKEdv7HF9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOU5vcVB0TGhpUGFJTmNn
            ajJLbXVQT2RkcG5qazNvMm1sODVIV3BudWlNClZTVzdHL0pPa1hBSGJnaU83UWcw
            YnVidTN4KzQxemxtYyt3UEhhSDVPUXMKLS0tIHRtS21BTHVEY1ZwZUgvaWZtRVJV
            Z2lxRDF1M043VkN4Y0h2NXBNR09PeTAKxqvQnMss4uayfahOtiWhAe+eMOxEUt5Y
            hwvBtEyvq6rc8BSflEnlK2RQXHSnxJJVxoEqvB07eRTMShXVHABf7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qatpp7y6rrl248n739dsnh622jcncx49e4vnrusvdgx0un0t4uqpk40m5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T00:25:45Z"
    mac: ENC[AES256_GCM,data:QZBxDam5PoUm1mMIFXd8v/zWPOmm1BM48MjnZJUVLR4VTbDcgvf53GysAN595RSPZrtry62MNi4vJlIRoaWLiozUcc/c1W7ixY8QRNsvmkyR1qF19utHJDCGzDQ8BC0uZaZ90Qv9orZ/m2A2TlmD9Zxu6iTEqHKc11KhKDIClL0=,iv:QtLxUmje1t/NqnnGgzW6Un4CHHL07zZxe3zSSFTgNB0=,tag:+HhJcx/vOZ/URuMPuDK3BQ==,type:str]
    version: 3.13.2
