apiVersion: v1
kind: Secret
metadata:
    name: actual-budget-secrets
    namespace: apps
type: Opaque
data:
    openid-client-id: ENC[AES256_GCM,data:WeRQ+/Y8nhikYpL7HLiTAkJa7pAf+z72r1z9tamS9Miv8DDlhq5/TuavWxYuT1VKNmG0zw==,iv:8Nzvqc18Ra0LgRDXu1KLrtq3l+fSXrTCrDnfw12rlPM=,tag:Cy6+AVL0opLS1tJztf7Gmw==,type:str]
    openid-client-secret: ENC[AES256_GCM,data:hes+s6RYXrsoxpzhclxEHd2AHxJG2tbyrCv81iL5t0qXz6Y7lJQvCdIfuNMlxKARcFf2aqWNlfcxgUdeXB56pcKPCiJyaIkido3lt9JJWbZ7obMBangCXA==,iv:OmdpYlCV/AVXVBk6szUUhdulXhM6qBXucolaZTGr1gM=,tag:u52TKnuXuwwUsSD9F54BFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNUdwcGUyc21MM29SL1pI
            VkhRMDM5Z3RGR09zem9uZVBkVnpiSjYxaTBvCmEvM2xxUnNOckZHTDhtMmk0dC9w
            d3FJVzNnVjAvcCtUT3ZqVVhYVGpoZFEKLS0tIG44Q3dtYitURnJjZC9xbjZkdnZL
            V21aaFlKQjRJb3hsK21ZWjZhMkUrdjgKe9kg9nV7bSfonYslaFZHCD9lr9i7JYxg
            b39dO/S7mgmop0jupYVSQIOSMQGZ9EHvvAG0SyBzdAxb7Spa99K1fQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T01:46:12Z"
    mac: ENC[AES256_GCM,data:tIXHbwdBKZ/tMnXb7xMCPIiHWZQ77vI8tUgrfkpYWsTisJgVx6l9+/n0bcCU8+voKCdoLgAEOi1sJ2w5gWcnYfQ+BLaCoJvdB25TVDnqwcy/bzEctoiaeqE+8J25hHx8ck91Z+MKZDx6VQrHy06p126OVUUB6nK9pvbI4gEwt/o=,iv:W8fVsxjCRC3cqKR9gYjqvozFHpzvUWuzaM+fQV5skJ8=,tag:uYo8goOz6kfvYmVGZJykjA==,type:str]
    version: 3.13.2
