apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.sops.yaml
  - deployment.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: cloudflare-ddns-domains
    namespace: apps
    literals:
      # BEGIN SERVICE CATALOG GENERATED DOMAINS
      - DOMAINS=argilla.reza.network,audiobooks.reza.network,auth.reza.network,budget.reza.network,chat.reza.network,grafana.reza.network,headlamp.reza.network,hermes.reza.network,homeassistant.reza.network,homepage.reza.network,jellyfin.reza.network,jellyseerr.reza.network,library.reza.network,lidarr.reza.network,mcphub.reza.network,music.reza.network,omnifin.reza.network,prowlarr.reza.network,qbittorrent.reza.network,radarr.reza.network,reza.network,shelfmark.reza.network,slskd.reza.network,sonarr.reza.network,soularr.reza.network,speedtest.reza.network,stork.reza.network,syncthing.reza.network,tasks.reza.network,vpn.reza.network
      # END SERVICE CATALOG GENERATED DOMAINS
