apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secrets
    namespace: apps
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:67OnGy+x2/G5ac80C5P71iwZnrmzeMmLKUWQXw+NC5Op37A81tgjlcPol7kj77CYcXNAQQqfPXY=,iv:cdQwyAeHHLH/BcslgH6VgzBSaWrLfQvs9s0Mrn2ZNRs=,tag:r7iuBTw5QZF7X2vS1NpCEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSmZ5bVZrRk1tU2FvbDZp
            Q0RNUk5zYUV5NnJVeTNyWXF5R2ZjSXdjTkdjClB2ekJKZ2grUHJuYzdFTnBJeS9m
            WSswbmNDV1A3amtjd3VwRDJzTUtmemMKLS0tIEVKUjJqVDR1S0VCQUdWb1pweXdR
            QVBubFE4Tmo4Y3lwMGpxSkFjY25rRVkKeOm2D/R0v+0ZDCHY718Xcs0ZNCxxOWt9
            Ve1zd8UHBMQqwzwWbvgLxiThb++5qmki3w2esbLjhoVgeBSYUwC1GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T01:46:15Z"
    mac: ENC[AES256_GCM,data:JJedHvpbLN8XO05HSCrvvWrf/6ePsS56n9r5aJQIThYonGzgPQBpyGSIV909kmoqCnO8wlBnHDJfoOof6vEedLDd9nS+x2d3L6Y0khXM6jC2Xb3GZeuEYVYF6GU1umi8UXKxk1ZKszc3w9ErLJ+Nyu2x6+TasnhLpIrq2cUe0Yo=,iv:XLy2jyw9Hmy892IQvIw775dtRD8GfoySikvlcpbaY4I=,tag:DE09I+K84/vTGMrA1YPnKw==,type:str]
    version: 3.13.2
