apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secrets
    namespace: apps
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:J0kMxMbvO/Eh+qtIpqTU81ODXj5YUmpQNU7mbA89aiFEyb5a/h6HL+6WSJQbwBY76Q2g2mk3VwE=,iv:cdQwyAeHHLH/BcslgH6VgzBSaWrLfQvs9s0Mrn2ZNRs=,tag:sqBxk9l0/d5+Z2vOxAKl5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSV0JGbURvaTA2Um0xck5Y
            NVdvRVl5N3oweFBrWkJ4eDk0MTJsNDJraWxNCks2WHVnWkhmZ0ZiVis2WVR6dHB4
            M0k1c0Vha2ZGT2UzRy92Rmh3Wld3ajAKLS0tIDVpY0Zsa1graGNsRUZETVlkU20r
            czNENSs4Zis0eWVIdjEwUEJBR203SDgKruBG1M1wVlnWAYwKuGv6yS+9wgD/7FrK
            5OE1x6DeraEtUj7sfAYOheho7OCJVJGtJBlc+UKu3aWSsTQa2ZE2rQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qatpp7y6rrl248n739dsnh622jcncx49e4vnrusvdgx0un0t4uqpk40m5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T00:37:01Z"
    mac: ENC[AES256_GCM,data:aOf0mBI3olyl5/7aDb+VaHwXEce1782XZLEms1IpGiazsv7cq1dU+dLeBs1STVINHzKunK5TRVOohAqbjEztzmNsuIyp2ZJz/A1+rINw+tM5MiSbmlFUzgd8c+LeFJ33KjeIrn4amD0PPCMFdX2vRoAm4/E27+QzWSV9Mgj5vMo=,iv:Ytm+yj2ifPzkw7BmF7j9O+Vc5aBi1SBIg3uCIlzjSr4=,tag:kF6Vwb7dN+lvXHmBkfhQSA==,type:str]
    version: 3.13.2
