apiVersion: v1
kind: Service
metadata:
  name: slskd
  namespace: media
  labels:
    app.kubernetes.io/name: slskd
spec:
  selector:
    app.kubernetes.io/name: media-vpn
  ports:
    - {name: http, port: 5030, targetPort: slskd}
---
apiVersion: v1
kind: Service
metadata:
  name: soularr
  namespace: media
  labels:
    app.kubernetes.io/name: soularr
spec:
  selector:
    app.kubernetes.io/name: media-vpn
  ports:
    - {name: http, port: 8265, targetPort: soularr}
