apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secrets
    namespace: apps
type: Opaque
stringData:
    service-secret: ENC[AES256_GCM,data:c/A8ve6t5bxnUCQNR/9hm2fmzOP9UE2HAuWJODci4FlGwaIDi3GzNYt+lnDVqcjdej/A8hBpuc4Cf0aS6STIJw==,iv:J+db7kaUpndJboiuvEj4nrPZDJauGlUdEsso8Hhxtcw=,tag:SLfFB8lsDApr+2I6/wanpQ==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:brUk6ZMnYRP0Xa3VDOmcMGjsUuvnedWlORdHz3qOwr1oSUOYtnFDP+WdvCNzRiMxdn8l7Gd197PI/r2dtP8wNQ==,iv:vP9JIha9DEBbLgNa5CCpC/Q+f0U0Qx3JlJzTerJmBbY=,tag:7PNMsyKrYVajVIasKGUc9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bXFyb28wSUNxWDRrL2pG
            eHplL1VQV1ZHcUFHTUo4OElVNXFMVTJPelJJCk91VU5Vc3hZbkozMWVYSm9GYk9p
            UXBnS2srb09pNUJjcEdqVkNNaFN3d1kKLS0tIDhDVk14eWNiUGtxeUlBN2hwSUNh
            Tm5ueitaYno2TDM3Nkc2Vnp3dFJEcEkKDJdl/xSMUTQr2criNIDGQeqmK8VBaYlp
            TCVH5KbfxWQlBY84VJRyIi8cK4ZZD+Bsv0xTPSxuUHQGlqT8kbGZlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T02:03:31Z"
    mac: ENC[AES256_GCM,data:dJV0X2kDc6FQqli03R+wPvdDyDdfNOlrW2e2xZxgG+nIsL4pmS/IAg3r03aPXnd2898am3UAHb0SCleq5nQzB71n+FO0/kQqr+84Hd6GRpc4PZSNi5yoLmHLJihx8L9iZSpLOWn9cfZnGLy3xPc6nhE7iKXV36u7kycfQvBdhaE=,iv:4j7Q0c7RxLuL6IR9sv7FnD+thakgdKHxds2NKgpZDrA=,tag:gW6l3a8tHHjy65/g7DRsFw==,type:str]
    version: 3.13.2
