apiVersion: v1
kind: Secret
metadata:
    name: navidrome-secrets
    namespace: media
type: Opaque
stringData:
    password-encryption-key: ENC[AES256_GCM,data:Ibp1AfRkGOGL/c9EcU0QOWf1wh11putPYcx1tG+2yH588NzS4EIRj6DlLxnJa5xs6NBS9weMQjlYhwcMWfu5Ow==,iv:loyiI2Vf9mdP16agK7OXvFW0GHCee1/FbyqRBaDzU6M=,tag:4DtlK+bQhasY+k4QYm/AsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q1VWK2RRWHplUDZQSGtu
            Ti85aVBqcWMxbkFXYi9LVlZvOW02bzM1TXlzCnc5enE3N0xERUMwQlE2QmMzdlZz
            WFJnNHYxejZnY2sxaGEraVZHbGpBK0UKLS0tIGhlSHhKRkZFSW0rV1Jabm1PNnlN
            akwvcVJzbG1WeS9PSnJRZ0dUQ0VLck0KtIO+vHFM6WGIaKGWMAYCROCHtfGSnA2Y
            CghNWir8PhZZxhlGRjTaUr2FfytCYOlNB8kKgNUTIcTNeJW/BGnI7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T22:26:52Z"
    mac: ENC[AES256_GCM,data:yvAvAZeUPU5Jf8/zodWLnFLjtnzAWMK5doIUcdZL/91YqdOb3N4lkFtozmYOtZof9EC8KQO5qkbbKT2AjeQ8MTBrdeynxneolPO8KyJZes6WuuXwmwC84oFtncCuqacdkHkUvfa/XLekjY3BlAhi3EHxlR/U0tLxS8fG8z/kB04=,iv:Nd5idvoYw5r3wYQfN3xi0FrwIzshr4s6fcCF6fxBGwM=,tag:OBqX++k05ro91/Peok9A4A==,type:str]
    version: 3.13.2
