apiVersion: v1
kind: Secret
metadata:
    name: syncthing-backup-credentials
    namespace: network-services
type: Opaque
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:PDd+UTnnRWMUs8U16giCg/Ns4cD9SI7HRA==,iv:CDvxa0ESecO8Q1yosTRJoiVswliNxoe0FT0aqE3qPzM=,tag:8Evyuhs3Keu6C0iBC409HA==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:aPOGdiqlHwzTE4l3jjHubD/tWPgIftjD5Sw91yh87Q==,iv:hX47tuNAPghAD9ayoMEU+ansXuyzpihFr3nVsbHY+bw=,tag:x+yDh4hb4zB4tFhj5SXEgA==,type:str]
    repository-password: ENC[AES256_GCM,data:zL0X68QhTOIvIDgTYl8uS6ZUPF/kQ4zJFgEmBJKnn38/d9HVW5beH77EU/GF6Y8xvv70buLj4QTt+0IUUYQ0wQ==,iv:14jnfCbZvoA6VQKeSGLE8xBpOKYxNciTFJGnDm75Naw=,tag:3ONqgnksoovKM0oFfEQOUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QTU4MXdFVDE3MG5OaElw
            ejdrVjZCR3Z2eGx1OXRUOURka0w2ak43eEdjCmNBVWZzY2V2WnpBQlA2QnhVRXp5
            NmpYWGptU3B3WVpGOUpJUGZtbmQvOWsKLS0tIE5zUTUwL3Q5Z0gvZVNKOUJrN0FK
            bFpxVW5WZUZtN2xuWE5qYStCSEY3K3cKo4dc7FtjADbtsdJ6OG/bGhvCD6GxH6Kw
            iP4HzlDSLkCPS6+oE9rKfQBbieSylBJ++1oncshX9k4uWDFLgVARXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T16:05:57Z"
    mac: ENC[AES256_GCM,data:l8sVwhLBbOA1+d62gihpqLyYtQ1cvosd3Gd4k4WoGSFomEt5t2kmAlR0Zxf51mx2tARYUpLN2QZKhtOi34pk8bsLStLyYbwQXNCa8keAzuJIceGyNMk892AB44HmDWoNkWnq1+YuirGOo0E91K2KQL52Rir3EdLXpSabtB4hpzs=,iv:SKdc2TXfPwyvvW20HN6RE6TMN5qGgxXif/R0c68ydNI=,tag:dbePYjEXArYAIc2KPKXUTw==,type:str]
    version: 3.13.2
