apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - credentials.sops.yaml
  - cronjob.yaml
  - freshness-cronjob.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: syncthing-backup-policy
    namespace: network-services
    files:
      - backup.sh
      - excluded-folder-ids.txt
