apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: media
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests: {storage: 5Gi}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-gluetun-state
  namespace: media
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests: {storage: 1Gi}
