apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  interval: 24h
  timeout: 2m
  url: https://github.com/kubernetes-csi/external-snapshotter.git
  ref:
    tag: v8.6.0
    commit: 78e32cd84e0abec2621924a30e38c755f93e180a
