apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-snapshotter
  namespace: flux-system
spec:
  interval: 24h
  timeout: 2m
  url: https://github.com/kubernetes-csi/external-snapshotter.git
  ref:
    tag: v8.5.0
    commit: c8edb651faee28c52d0f61796764b649253c988c
