apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.sops.yaml
  - pvc.yaml
  - workloads.yaml
  - bootstrap-job.yaml
  - services.yaml
  - route.yaml
  - networkpolicy.yaml
  - monitoring.yaml
configMapGenerator:
  - name: stork-webui-config
    namespace: network-services
    files:
      - nginx.conf
