apiVersion: v1
kind: Secret
metadata:
    name: stork-secrets
    namespace: network-services
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:4WUnJd+I0bUfbk54klVwezWgVIaVtVUOGgs5IqNd0B2hfgLbeAtDJ90DHDc4WVKp,iv:eFCgSI0V5qldxMWPheS7L8Af1BtwM+aPP18HuLjcG/A=,tag:pFxpINMB6xfyhLbkaYBwxw==,type:str]
    bootstrap-server-token: ENC[AES256_GCM,data:tjGN6C8egqjUAzvvavVIYMkl/vCcz+9bussB7Wki/A4=,iv:qRnXkmkWm9eZAW1RUy6yuMr2aZLptjo/mfPgBa+gVZU=,tag:Ur1+4zg1OtquQvO79zkxbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bG5La3ptVEdGRnQ3eVhM
            TDU5SEdwdS9Rd05CQ2JXZXI4SnFFZERkRVJ3ClVNWVQzYjlsZXNTd3RlMlh1QUF1
            MDhxOXhDc1ZwaklMY2RzV1pwOFM3aTAKLS0tIFBZL3VYalpKYkpkdjJYcmpONG9C
            ZzlEV1E3TWdBTTJwQWZiR0JOY2dCVEkKKyc7+DiiRVPWMUrGx612tfFEYmQV7WE/
            DjMEzJeNmBcstgsdZ+EE9A3BXjbx0NELh+EiC9Z/ezgskdsy5sWBZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T14:32:54Z"
    mac: ENC[AES256_GCM,data:ABGFXYqaszhCLbH/jKXCfsdUJkYHVHOFXTPVEcr0zEeKD4BzsVR0yqysDjDDOUi1rOup0O+rac0+SyP3R2y8hFL8P1jPXU/Hekzy2wkXeY+1lzcIfFQy/8Fuv2o1FV0WOALFcyzR3CQoCF7/EwMjBh+qfeGZHgzH2xR6cj4d2vo=,iv:oE5awMBkBniYRW9C/k+QrK/e8b7vNrVp5rAGDxaMSdE=,tag:tXbcmsVp6NIpg0l94zhMUg==,type:str]
    version: 3.13.2
