apiVersion: v1
kind: Secret
metadata:
    name: samba-credentials
    namespace: network-services
type: Opaque
data:
    password: ENC[AES256_GCM,data:7Z5eEQF2IyIoMX0R,iv:RY8D+Ah8dbnDF3mv9A0oR5VayaPlxYUwY67qOkWtINE=,tag:52uFHi1SVMPJr8qkW/PLzw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSGc2SENXbmRCLzhYdVJD
            WTJUeld6TTFCeWxLR3ZwbTU5ZXBJaDk3dlVzCjVRRWxJR0dKODBRcmViMXZTNll5
            aDhRbG0zZ2JCVU1IOUVJYWYwUFRhenMKLS0tIHNWZ3lRVlZlM1VZcUFFcEk1OWlL
            NEQ0RFNLaUVjMGZsSklHeno3bFREZGsKG+xOBdWmJjgeaejn/mIUJ3gBWqbojQwK
            mC32J/+Yr+gyQ3eCTupg7sv835ftuYsa0fI2jG50LORvl3zUMnod9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T01:46:25Z"
    mac: ENC[AES256_GCM,data:6/ViZkPsb7tthiFP98RaWzp3hvN1FYboVRkrE4v1qkAuCemXklBbfrLFIA+4iAhziHjfbQAQ+b4LlNsjM7YZGKuJjArEyqa1EElCsydlIiL9aiykgp1PgB8rDL0i9XO2QGNXkpxiodVZPgk+GHW3xkmTs8DEaciNyHc4TcrF2Vg=,iv:98frq/LzEyGPugC8AU5s8VRSAe+cUgCnOxTHThhxqdo=,tag:iN+CuuWlGh37I2p/tQ+Ldw==,type:str]
    version: 3.13.2
