apiVersion: v1
kind: Secret
metadata:
    name: samba-credentials
    namespace: network-services
type: Opaque
data:
    password: ENC[AES256_GCM,data:Hrn5A8zTGLiQRcfA,iv:RY8D+Ah8dbnDF3mv9A0oR5VayaPlxYUwY67qOkWtINE=,tag:HOIPwIci/U1+SKhhBYt+VQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N3NmZzc1N2tIYUtVTjVY
            NFh3WEE4ek1TanViZFNvUkNheitmVnEwUGhzClVHUm9LUkZBRmxUTzNuWk5MTmI3
            a1VMcDg3bVdnanB0SmVtTDBTY3NadWMKLS0tIDg3ZzBwT1FKZUQxTDNaRXBOcE14
            TGJWSThtUERSZU9FTTdWa3YweWMvUFUKpynTMnVgQW3yRFAT/CAMTqQniSi7pjH8
            SoJo7TybKXnaj+igMGN95XdMi5sGzc407u3NhLUKDDypI8qZb481gg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qatpp7y6rrl248n739dsnh622jcncx49e4vnrusvdgx0un0t4uqpk40m5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T02:59:58Z"
    mac: ENC[AES256_GCM,data:RgPPvtFZ6f191l0Vi4aNXooTZ0JfqFtHpIc+OwHOY0p2KuctKVu6cIrjj0my4WlhQz6w/sCpn3DkU2Wc1OLVRPGF09LM7YWgXrBu0kJndQlN9T5wsITI6f55+vhbTh2/MUk4zZKPQz/Evcy5s385kou6L/yphFR/8KsR785fERc=,iv:Tlrr5OWPY2CaDBpOnQg8ueRtqGVQrB9GkokfW78o6V4=,tag:mb2eMtWT00hlP4ByHAAEiw==,type:str]
    version: 3.13.2
