- resources:
    label: Cloud library
    disk: /mnt/media
    expanded: true
    diskUnits: bytes
    refresh: 60000

- resources:
    label: Local downloads
    disk: /mnt/downloads
    expanded: true
    diskUnits: bytes
    refresh: 60000

- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: home-server
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hourCycle: h12

- search:
    provider: duckduckgo
    target: _blank
    focus: false
    showSearchSuggestions: false
