apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 24h
  timeout: 2m
  ref:
    tag: v1.6.1
    commit: 8bb74df00e56ec8f944d48c25e6c1c9c2f6848e3
  url: https://github.com/kubernetes-sigs/gateway-api.git
