apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library-apps
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions: [nfsvers=4.2, hard, noatime]
  nfs:
    server: 192.168.1.2
    path: /home/reza/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: apps
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-media
  volumeName: media-library-apps
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-data-apps
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-syncthing
  mountOptions: [nfsvers=4.2, hard, noatime]
  nfs:
    server: 192.168.1.2
    path: /home/reza/persistent/syncthing/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data
  namespace: apps
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-syncthing
  volumeName: syncthing-data-apps
  resources:
    requests:
      storage: 1Gi
