apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library-media
spec:
  capacity:
    storage: 1Ti
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions: [nfsvers=4.2, hard, noatime]
  nfs:
    server: 192.168.1.2
    path: /home/reza/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: media
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-media
  volumeName: media-library-media
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-downloads-media
spec:
  capacity:
    storage: 100Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions: [nfsvers=4.2, hard, noatime]
  nfs:
    server: 192.168.1.2
    path: /home/reza/media/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads
  namespace: media
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-media
  volumeName: media-downloads-media
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-books-media
spec:
  capacity:
    storage: 20Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions: [nfsvers=4.2, hard, noatime]
  nfs:
    server: 192.168.1.2
    path: /home/reza/media/books
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-books
  namespace: media
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-media
  volumeName: media-books-media
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-audiobooks-media
spec:
  capacity:
    storage: 1Ti
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions: [nfsvers=4.2, hard, noatime]
  nfs:
    server: 192.168.1.2
    path: /home/reza/media/audiobooks
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-audiobooks
  namespace: media
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-media
  volumeName: media-audiobooks-media
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-podcasts-media
spec:
  capacity:
    storage: 1Ti
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions: [nfsvers=4.2, hard, noatime]
  nfs:
    server: 192.168.1.2
    path: /home/reza/media/podcasts
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-podcasts
  namespace: media
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-media
  volumeName: media-podcasts-media
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-music-media
spec:
  capacity:
    storage: 1Ti
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions: [nfsvers=4.2, hard, noatime]
  nfs:
    server: 192.168.1.2
    path: /home/reza/media/music
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-music
  namespace: media
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-media
  volumeName: media-music-media
  resources:
    requests:
      storage: 1Gi
