apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library-network-services
spec:
  capacity:
    storage: 1Ti
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions: [nfsvers=4.2, hard, noatime]
  nfs:
    server: 192.168.1.2
    path: /home/reza/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: network-services
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-media
  volumeName: media-library-network-services
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-downloads-network-services
spec:
  capacity:
    storage: 100Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions: [nfsvers=4.2, hard, noatime]
  nfs:
    server: 192.168.1.2
    path: /home/reza/media/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads
  namespace: network-services
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-media
  volumeName: media-downloads-network-services
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-books-network-services
spec:
  capacity:
    storage: 20Gi
  accessModes: [ReadWriteMany]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions: [nfsvers=4.2, hard, noatime]
  nfs:
    server: 192.168.1.2
    path: /home/reza/media/books
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-books
  namespace: network-services
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs-media
  volumeName: media-books-network-services
  resources:
    requests:
      storage: 1Gi
