apiVersion: v1
kind: Secret
metadata:
    name: hindsight-secrets
    namespace: apps
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:tWZ7t1XLHsFHs4+k5PmIa8GtSZH0B3YDdiFOkL2Toec=,iv:mqaBBwYTK88ZhmhAZofBB/6noV04zJ5drI9U9JVv+6s=,tag:dGEEbslFXTXS0zpxy2zIgw==,type:str]
    database-url: ENC[AES256_GCM,data:TjXOShkwFrMMowIeFFS6gCOPKWuqWznVFkC5DpKgohmBVYm5Uahu93evcm4wv0O3zdlBbyuLB/Bjb9jxe4iXTwiKDdkzHIgrpV6b8TL7mCgCGPzJt2qnrJJ0Qg==,iv:oKD+PQfMIU0Il0HQ8yboYEPgCqUOrZoaEzJcTyuEuv4=,tag:KU8q6LTCjse2o/KDLi270A==,type:str]
    tenant-api-key: ENC[AES256_GCM,data:ZINfcGQK8zJloeA4+bfJ/smBzPWGxj5xmoJrKi/6tmU=,iv:9PG8iR9FniOrj2Ms8qh9H9LaMozL46PrXLk1wk1qmSc=,tag:e5o2nYULcDghV/XAwa8ZjA==,type:str]
    llm-api-key: ENC[AES256_GCM,data:eIVkdnCUy02ZLpsdmu59mkQhAoddDW7W7O6mtEV5neRfQVk=,iv:XmOHUN6zGl5UEGqld6+P84kUU+noRKoXe4MPjlPffKk=,tag:c3H4jalduOeh/x9u1P1xNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMm4vcko1cHc2cXpxbVhz
            dWRzM0lPUlc1NzN2cHhDZDZPYTNHNlhmUmtvCnJaZFNVeFVvN2VUU1RtUFdlekZC
            L2ZnNnZqa3cyazE5MFgwSnRLdjhnTVUKLS0tIDFUYXRXNlNhNllSVW5majc1dHFF
            SHRSRE1kREd3NjdBc3VKK1BBWGlkeUEKlRxw4nb3MwGFOflch7IqqSEvW5ynAr2y
            NAG2FvUeU9POx9hjc9rGN9fScOn9qlni8eWj8YJFYaIwCxMgw1WHIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-06T18:39:53Z"
    mac: ENC[AES256_GCM,data:jhpjd97uCgvYmfj5TT+8eiU/D+0WqDr0p4qYe91Co7pzPbKOD6C6kN2J1+DReU2pOYHvmf6W85cYqDYctjt1ANSPWIt3AWlbBtD1y5Ok+GFIvrNOh0evpzlbd/xVJckNckzjo2UDLdx3D5uHagwssNfH60Iq0w3eNwoujC/xjYA=,iv:NvYwVYxrnfonVHsO5BRvYTjXjmAN7g8a5OgEnCEN4yg=,tag:bnfmoR8VrMw5MMNbAspD8A==,type:str]
    version: 3.13.3
