apiVersion: v1
kind: Secret
metadata:
    name: cyd-dashboard-ota-secrets
    namespace: apps
type: Opaque
stringData:
    secrets.yaml: ENC[AES256_GCM,data:J2oxuBHvGqqmNqsTEUIMh5kRkExxxY/fmMU2BWrvgpw/BBmsACfTe4HVkTdaV7efKwJxth0pRlpsqe4nobd/bAiW2ABDNA4iPqeoDFKxqNo0ZXJIt9Cqkt+80xNrAP5lvNWWbVFnRMYwo0Gx0EUIuzCgAbnVWfxvqlUNTryL7MwSXD94jRMMRZBLG1fRpPS863ybQuXSczmNkfQ2Af+AkBPLRhY+yX0prjPrUzZnkXh3+tACXtJkM0KJ8UVlSi1YBI4J0fUNFIPKjs2JhRiZFq+xpFiHEvPvf0AYGy7t9XC3yy4CXh/QDZi9OT1U+h3KJtSyjyyUj7PsGfzLH6Ll+4UiF09z,iv:0QV6Fe72fsrQFtwmOHYO299tGWyTp1jOg8wp0cqVj90=,tag:NRM/sCj77BHLNk2+jaX5cA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSjV1VzBrYXMxUE4rUCtw
            eXMyVGdVRVQ4YXpQZE1XeWwxamo2dnlMMFFBCjJXRUJaTW90RmtZSVZwdFZzdDlQ
            TUlvdjZMcVZsZS82d2VoUFpvbWVOQVkKLS0tIGxlcTd4YlUxZGtFUzBqYVpTYmtC
            MTFHTW1wZFBjdG9xK0NBN2tSNVNMK0kKBeVG0U6T/bjk1j4BwVScbqXFb5k1Upbf
            r1NqF2BkvF/8VPcOv/V2GSa+8mh/wRcBMpn4IonwQJs4HMJilZqWTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T19:01:43Z"
    mac: ENC[AES256_GCM,data:yqPnQ4Jwuhak0VWBNIQvGSLt2u9tkJwhSenuCe4kMrlikCb1LnrGPee/0nTyEiPOkkcXgiE2X3/ejC5waU38lgQQJGL6+Xvr5dqHwl9csIzJxsUpa7peGxBl5gEOSzjT0+kJzOI4LloeiHldMSHJHUeYEQX02rFu1tCNgMh/JQc=,iv:hGmR5OciCuqaymuDKRq93l9Am8B5Kg1ThynzZi1Q+Rg=,tag:O9AikVWqB6Lwi6Xx1R5KJA==,type:str]
    version: 3.13.3
