apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
configMapGenerator:
  - name: gpt-researcher-config
    files:
      - researcher.json=config/researcher.json
resources:
  - secrets.sops.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
