apiVersion: v1
kind: Secret
metadata:
    name: gpt-researcher-secrets
    namespace: apps
type: Opaque
stringData:
    openrouter-api-key: ENC[AES256_GCM,data:Dmjg/snQk0N4EHvhpXDiYduqxtizFsZuJD6VrdgcCH9CjLhKktO5ZyNG2s+N5lyw9RV9L3IO/8OUxofvBoqas0KbYC9XGKFShg==,iv:Hza3FVhzl1e86AunsD/K31ao31+fvqji9CrEt9hLSDE=,tag:vymedsP3s5DBj0jQEIWlAA==,type:str]
    api-token: ENC[AES256_GCM,data:W+yLiybElcwUbtPM6tpt5MhxqgAsnwnRe/8m6ONdmlKcyo+Y2qT4jcATTuW5HXREUSIQA2Vt1mPsuPsJD0xnsQ==,iv:fb0L4KXsW5WEwoGbrkJCZRO3PwEQcjzhGp/r9ItMT78=,tag:DqBtDxlvWYXjeTSHFziFlg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMytJZlc2Wkwxc1RXLzBa
            OGlQS2Vvb21YeTBHWVIwTWlNTVpoQ3ZxM0dVCjZNYWh4WFFKOFZvbWdZQ2pMQ1pm
            OXJXR09jZ1M5ZnZ4THM0aHhHd3FqQVUKLS0tIEl2aGtLN2ZHNjNoUmpiUGNVV0lj
            c1BwVEIxNTR6WE5oR096Rnd3dExwa2cKmmhArTCLN3+tcrFoNgxS3ae7OMJj77GW
            IcKDHC2JmwXvh03ReLJZd+B9Es0Cyut84+nROFvvhIUS0ANCCMgY0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T19:40:26Z"
    mac: ENC[AES256_GCM,data:4CyN0pqyEIxV5R9HycP5V7nM+HfZlSFB1ytX6JQkJHbK6R1ano73lKd0veDFBvv8JPZzSQvErz15xQElRvJMH1snYxJlgwRXIbrRTkZRvq87zUm99gtl13wMy7pHhbOznkPXYeYOeuXaZUMcAhU8UZWikEat2z/VFlrkww0TY1E=,iv:QUU7Z8zKypUrIJRgNMAcv2EhklIHjvEC8ri+IMVE1+A=,tag:kBNJkatNIOAwY4dfd7xA6w==,type:str]
    version: 3.13.2
