apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 9router-data
  namespace: apps
  labels:
    app.kubernetes.io/name: 9router
    app.kubernetes.io/component: application
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
