apiVersion: v1
kind: Secret
metadata:
    name: 9router-secrets
    namespace: apps
    labels:
        app.kubernetes.io/name: 9router
        app.kubernetes.io/component: application
type: Opaque
stringData:
    initial-password: ENC[AES256_GCM,data:WZBfGFTjweO53G0HKZoo8+V/ZKVZoycd,iv:OoAtaSfQsH5nX8gAkxB4QoyVssx8N9zE/PflSpI1NwU=,tag:CgZrIPzwkF0jB7zV3g9xwQ==,type:str]
    jwt-secret: ENC[AES256_GCM,data:BclxjrJ+Mf1HCTkALx3R0gKGM2W/Z8j+/pMmJ5efTf3eTAPdmPKC5n0CdKvjIAEfSwvfFdCkHgOxhQhxXILD7w==,iv:08It/QbfLkWSInnFGy2Qtc3zMuQExysR7eX5umOfmko=,tag:q2XBsn/rRbKkE2T7XB0k3w==,type:str]
    api-key-secret: ENC[AES256_GCM,data:35oJSWMnym/6sZWFsUB4eqp4wzKm8PpXSnXh4kiw2EBTd7jtG/Uoi/MMNwySuHqalXQKGEP/k2bcrSagA9y+pQ==,iv:EHFWG4ZtDacDmYGT/2lZQ4JXOqSihx6jD/n12dEp1lM=,tag:DLJRyM6nAFRHGwNGk77IcQ==,type:str]
    machine-id-salt: ENC[AES256_GCM,data:o4VJoWy5gqmynomMk2srBmn1me+s2znvFBQjA9F/Uqk=,iv:TkWhczJDa8nYJpBwY1FUXOJLEQbSxRj6+qmMeh3DD5E=,tag:kKs2vVsbPjpeBfaz+8wajw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SGJVTy9FTndmS09jbG0v
            NXpIU0NtVFMxdnRJZHI3S2hJK0d1S2wzR3dzClQ3VG0yekpGWUh4TkN5dGFuNFZV
            cjc5L04yRXVtaVMwdFVOZ0xUMGIyYTgKLS0tIER6c1pHa1F6TGM3TkN2R0psWjdx
            QjFJdjljRHJibk5VTzZFVU0zWVhOQTAKcI9HQ3F52p2nYZHY5EVxMwSlV6KC2dzm
            qsZCXAuoRmw1mfm+DzB8J2KqgrxRDZZAN8k1d6sPSA9aaxDd4RjvwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T21:34:31Z"
    mac: ENC[AES256_GCM,data:XM8AaImk3l7rOcPMPf0L4JwFQKIRtcYPSs+QNv+zna68E93YZADkFmeFsB1aZTBqDi+8r6VFfP1nFow+6QrloyCmNPXrb3KcVjjdF98cHRwhAKSy91qeFLWptFlBA9x20TYq/MwOEq0CJRRXHuoNupXds6WZZQHlPCBwRdbbR34=,iv:GsZS8mQ+oFIaLGZoyv7jXCuDHxCq8+pKPBhy2Pt++Ww=,tag:7JASE2taaIwhsBTf5Mboag==,type:str]
    version: 3.13.3
