apiVersion: v1
kind: Secret
metadata:
    name: duplicati-secrets
    namespace: network-services
type: Opaque
data:
    settings-encryption-key: ENC[AES256_GCM,data:x3uFUam6XqGiWVDy1c9SRX0Kouo=,iv:LKu60usIz7E8XkXHRf0zxlmuBnt+zvRsFWAMCKnA01Q=,tag:kS7Cz1y3l9nQY8z9Sfx1gw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwa05TNVB3U2Ixdk9nZWJF
            MWdvYnRXOXBWcW9BbVNwR0h0ME1heVdxVndBCnV0Q0pQdGQ1QmtNZmxSQUx2eHhF
            djdiNGVHbU1GRmZhNEdaKzZnK1hBS28KLS0tIFMwZXh5NythRHBMa0I1emw0ZG1L
            Yi9nd0VKNmEyVDNrVnNMODVFQlZkaTQKAflzA7mvIKFERnOoQ53VdXCNl6Ug2/hw
            jwN1M3KYgiF3NWuNydeXfUizxXiuqz8R5PmTJQYlER7H2hFnRIphqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qatpp7y6rrl248n739dsnh622jcncx49e4vnrusvdgx0un0t4uqpk40m5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T03:32:06Z"
    mac: ENC[AES256_GCM,data:gT4SX2uXyXB1BfizefqVbiJkVtYPAcOa0E6h7oNDzEHuqOztmmhOvkbJUiZxSoj6zO1Nqhbr6JZUaqDZm4HsX6YwQncZ12KFDsx1o8iF53kMA+106hST5f6y8QJCB5QpluAFR2xBY4uxCx28GQ2/mVF6YRav+DOQINsSjxQCkDk=,iv:eNxUpd4YbjPMZI5ebCCrSMskwpKQz/wcCnj3TwhSV98=,tag:XPA8IiSDo+obw3+V4iXY5g==,type:str]
    version: 3.13.2
