apiVersion: v1
kind: Secret
metadata:
    name: duplicati-secrets
    namespace: network-services
type: Opaque
data:
    settings-encryption-key: ENC[AES256_GCM,data:FWTM6rJ1A+LkCp334EG9CgNlVZ4=,iv:LKu60usIz7E8XkXHRf0zxlmuBnt+zvRsFWAMCKnA01Q=,tag:TB3zJEkU0b4DHFUU66gFJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSallKWWdUY0YwNFM3U2Nj
            RnkydlNocFkxcHVPOEI5eE9lZnhpalQ3Y1VnCkNYTVdyZm56Y2NoV1FaS2J6azdX
            NUNqd3M0RGJxYWw1QnQ2SU9sUVExdTQKLS0tIFRhcTJqUlF1dVFyZU9pWGduVnBl
            NnJ2aGNNL0N2b2dGR1pPVTZxaU54N2MKwDYnZjiTzTt6cXQPDS1wBbGdst2F6aZn
            Pm8Cy+iPDcD9WJ2rOd+dwXIpdTDqzfuAUF0wU3B0VRPQEHE/TQW7qA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T01:46:18Z"
    mac: ENC[AES256_GCM,data:25Bjewbbt616ErJ++4S84zCHsZ6dPIVRX+oatMVnkGk6VEnkLq91+k/UJ3C1Nu/I8GzaWJj2v+Tl5Y66km+kLNtsZvYFqte5pECAnrnXL44vSfbpoiQTilxfxo6TneKAmNr4fZ2cc6ZN5R3Q/HfA0AzrV+HbqXhKTFtsqiVrDPY=,iv:aqcvKCCTJsvigpNipEarG0AZsiH22nXhsUAjpwSEoZU=,tag:xD2RoukZyAOOrrMp6YhKnQ==,type:str]
    version: 3.13.2
