apiVersion: v1
kind: Secret
metadata:
    name: finance-display-secrets
    namespace: apps
type: Opaque
stringData:
    actual-server-url: ENC[AES256_GCM,data:o9Ru4JLHv7rKr/BZxOQ4BMe3vfhcW6Nysz/Sf1nUuReIGnUkUfXwqaXDxTCUdjtNzZkZYQ==,iv:b7dvsizAJDq6Kfmh9ht1OU3Slxv1bjvuG9smaFSM/h0=,tag:LJYDX0duHZfI6laDQ9o4qA==,type:str]
    actual-password: ENC[AES256_GCM,data:AWuUslOwebqzi5QfnI3rJYmn49kFoNVhjqvl2/1AC3iyYcPVxAk+27bWM09bLqwYT+7C0o9ksp8i1foDgcdzVg==,iv:XPkONBcsSyvBFYAC/huw4Mce+V2Z/NusoNdQOCpYYco=,tag:mxy8bk/pcyXnePQLJuD2vg==,type:str]
    actual-budget-sync-id: ENC[AES256_GCM,data:62WCXmaf3a5OFpoEZpxvRcZw5JKAF8O6diaB5pvpexhOjpiS,iv:7povU75AlH9Y3W/BRsqQi0QwqqtGM5vmoCmjmE/Dn9A=,tag:Rdkx2VWj64mvb4y6qaPWtw==,type:str]
    cyd-api-token: ENC[AES256_GCM,data:SbXATTFMDP2+zL8QsuxbXnxNgQ38UI113tNWgr69V0NSHRP4WyvsnVA0Ig==,iv:5veFoM4lF6G1ZQ72NVT6xzfixIqtGryFzKh6zOl+18Y=,tag:RLXNTo6aBGgAft5W27zWBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ai9jTHdDdFZKdGM5ODRD
            Vm83dGd5bitJTitJZXFvbzBmcWFINnVNbUdrCnptNnUvNEthTzMrZTBmZEZJMnN5
            Y0xiZ2hZeEVYcXdNY3dDVFo2dnJVbjAKLS0tIDBibTlrK1c3RHcyV0FudCtIQWdr
            dlIxNHhrcFQrMFkwbnZDRjR3cTd2YUkKpvNoOF6dT3pOlBTgUpJy7kgDh8ekq0eE
            +WWv0jbWtivazRV4INNwNkYJO2Ua5qW1mQM87YlWChzQ/ExWSRBlAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-13T17:47:36Z"
    mac: ENC[AES256_GCM,data:xhkgBJmUuhaYeqCB8VbojAO9kPxwFwL8SmdhPKO9/9G0sX2JauxJrKdq50QvrLc0w2RTZjxuA46lA2/7e8Pf5yr7OXr67yVp5M1TICi35F/4ig7ajvEIQGzOYcfXdbNqlibiJA6z7yUQkRd30TQfhjhJBxaQ3kqiIEkr09VFx2U=,iv:4vVDbWqTaycNJovzThA03Mo5NfGiKbj2epPC9QkcTiE=,tag:xCbs89hs9HIjJlEovkLr3w==,type:str]
    version: 3.13.3
