apiVersion: v1
kind: Service
metadata:
  name: maintainerr-tmdb-proxy
  namespace: apps
  labels:
    app.kubernetes.io/name: maintainerr-tmdb-proxy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: maintainerr-tmdb-proxy
    app.kubernetes.io/component: egress-proxy
  ports:
    - name: proxy
      port: 3128
      targetPort: proxy
      protocol: TCP
