apiVersion: v1
kind: Secret
metadata:
    name: speedtest-tracker-secrets
    namespace: apps
type: Opaque
data:
    app-key: ENC[AES256_GCM,data:kqVoXwjuDelu+BD3sfyWHwliriSaaKNYoVvKbchoPiKfd3TpckpuqV3R648EdvTvgwi/pBQ/Klezq73ANa8SNrDLBlY=,iv:hbXbDpJoDPqPJA52J5/5972sfRiw2sTpsPfXWGIZpCc=,tag:cqN4CiU9izYXFnkV4mIwPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQlZxd1ZTcHA5eUVhSXNW
            eGNITmVxbklFdkRhelIxY2RSWXFOSmJ4R3g4CitEczZzYXN2THZNYmVHVDVreWZR
            U2RlYnhxRU9ZNjFvaHNhRnJRL0xiUVUKLS0tIEhJL2svTUhGWlorZHVGMGc2TEVC
            MzlMMXlyb0Z4NGhXSUdwQ1ZhNlE4Y0kK5mhFYehz3mLxgKwPih91TOK11OjHAo6G
            HnYQ3rPUclBmU8Av72jXxbcyX1UIgSHgWl4rkP+cQygHCLLfgadyjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T01:46:27Z"
    mac: ENC[AES256_GCM,data:ysUH62dfaoXOWT0GkJPHfpJJKGkyIxaGFfKDy3MZLBpbHYZ67PFABWBYkviBmO9kPcVLDT2Vne+nspxuy/zqwC6YhzlU5qWL5u8VfkfEz/WK1Vwp67RMnaEk8fvbCtEIkKlKK9GqSTGW0HRb9YA04PLkOFp+Qwle8Y8uYRT6IDE=,iv:RLb38uQpzcxBfjfG6GztyacJbd2hIXw7fuFH/yTfsPM=,tag:N0xkIySkv7vPgurBWzCDIQ==,type:str]
    version: 3.13.2
