apiVersion: v1
kind: Secret
metadata:
    name: speedtest-tracker-secrets
    namespace: apps
type: Opaque
data:
    app-key: ENC[AES256_GCM,data:kfqzU9Iuz7ozZJKB8BZ2XfNwIV1poAWeCy/gdZc7rDxW6/ARvorx+2tSASVCx8m83xy4oHV+rzVwNKvHQTtuVEP5j7Y=,iv:hbXbDpJoDPqPJA52J5/5972sfRiw2sTpsPfXWGIZpCc=,tag:NEZL6PUDO0YPAn1xPK26/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbmNLVkpCdTQxNHVYL01z
            RE1BOGwvZ3hJSUFwNFRIQWd4T3gyOXQ0Sm1JCkUrRW90ZU5xeVBELzRpWUEzWG1t
            UmM2Y3laNmtycmx0bm05TkdleHA4SWsKLS0tIHNvN2pOUGVnZ09jKythdVN6Z0RW
            S20wLzlhc0trZ2tEKzBXdGdvMG5iSTAKo/ExFNokwb/GiNiVpBpwvBnNSBWy0ydi
            ndefWvqDz0HCjI6ZnSuIcmSPHJQAa3dqk+tSZiKw+Q8cL73/mcJKLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qatpp7y6rrl248n739dsnh622jcncx49e4vnrusvdgx0un0t4uqpk40m5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T00:25:45Z"
    mac: ENC[AES256_GCM,data:qA8j/okD2NopdoRJ/rrREP0XXg4KqK9/Ny9ZmjvVGrlrZoyo7wVFMVo6T9f6E1jpCAYBZhmvhBFt+bdCTSRrgffwEUleqy8ELxuxxJEo3Uw5B4xriDpyNc1V9EF2uZzKkklH4/xNMSRPS35/+cXxEbgyCbpqy8RxnBwIAZ2cwa4=,iv:Z40WHVBV4JIkFV320SwYYdzDNLzVDe0RuDKRaWKmi/Y=,tag:QN66V8nLNrYX9hcEvMJKog==,type:str]
    version: 3.13.2
