apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backblaze-b2
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:WbEDuKSFRGn9O+tIZXvXZ4hlUO3RlKAqPg==,iv:ZE+zDhXuasib9FkQ32erlMJn3UKRrJwqeJjj8Wzjb6c=,tag:8KB9Y5nSIGZzXPFvl3I/Kg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fAlJIQZnrgbFvPOV8V077p7S3ka0svr1P5Mhwiua+A==,iv:r3y+ZnE8PDKhoY4dBO9d00qXUNQvUjXII6/HUfhMCgk=,tag:bK6enflvocKZvIxdYvwyrg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:mnpYdWF8GBdhynNc5oWKHg5y4mkdx+qmbA5wu2bMIs51MYm+1Es=,iv:nJ23trlbopkj10VDCHwIgIrjyaf+10PHwJOVJfN40ZM=,tag:kMULrXMl3zthMKXi/xhIaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjMTRwMVpDV0FZWXF3V1VO
            NFNuM2ZEN01CNVd4TmFSakZxTDlGSU1WUENBCnRSVkNaUExGRWtLTnNiR1YvcTVP
            L2JoYmlBcG9IM28zeDlLelRMZEdiRVUKLS0tIDl5L3JQT1ZmemRTRlBtN0hJS1VR
            R1B3TThzd1IzUzJnczZlWVByWFRmamMKwx2vm6sIxI89BtXPzOxwkG+yFWLTpqiH
            tfgia1Uzc3Sn5cAVYapExTDU0RndmDt4Oo4GMiZ6y5kn1PEPTZYDdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T14:03:11Z"
    mac: ENC[AES256_GCM,data:/01fCxjlqTt0BXQE1EscIdln6mpMkHuyg2f02/dSNjJ2KJFMpqRvZgNO4weQLb5qLVn1QC3jx7jdR82V4ED8cZBwNmnt2942uEGvvHUc3igWNZq+8yh4WdUHgpsGfirTpSONfFWQgcrQ8StjUj3Z2jDgemx1dm+1eofBFpb9JhQ=,iv:UK/s2PeZfzf+eox6Au04Cuhi5y4nYlKOMoxG1PNQadY=,tag:t3VY/huOS6pwAcci6pSkFA==,type:str]
    version: 3.13.2
