apiVersion: v1
kind: Secret
metadata:
    name: vocabet-ghcr-pull
    namespace: apps
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:5cYU3ESMkwjNLoiBq+3Pja+kxFVkw8IyUt7ozV+C5kToCpGi+IwIgqwKVzmRUDDaRhvm3b3/zEmo5GLrvIsjkfwJGfLx1JFLvE5AKBBBsFOPIKuHWt9WAaLyUgQmja+tarPsN3Y4VVorRQpPlc/RRZNF2JE35eafhoBczjZ0NiroJ7Rv7KL084seYXpQ2vf7WIWDTvWNSBFe1mAVEx02tL7oeyFT80PtKnZ1HAiE9N7aa6g=,iv:Vo/c2SdHDiV8erfZHcU3lkJLhwBJ2Pk4k1YLlcTHBmI=,tag:o6Ldk7LTQl9f9vo/pBqijQ==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzK0R4dnZqNHBEWXhFZUFG
            YUxWeDE4ZThxSklJTmRSWVFkYk9pWnV4S1NnCkxKVmhSTVQrTFAyNHk5VHZ6VUIr
            SDFDNlBmNHJUSmVWOG1FS011bWhWR1EKLS0tIDhFWDExQ3RQY2k2Ykt4bFNkSTZ6
            MzFmZ1BjRmQ3SFNMSnA1d1RNSG15eUEKOo0Uhg4F49InMbakENvQCItCA3qDgYsd
            m0aEGs0SRwp61yVRtJw6KFzQDk5o1YGQkjJGm/AqWRfckm+b8fDOXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T23:02:08Z"
    mac: ENC[AES256_GCM,data:fnZGFjfIalcbGh1SVWXCHPf66+qynK9C3AR0/ad1M1rx4z7iLkoDaUYFwdMvd+rsXKhHcde56ieaDndcYAHogGZPHkkphKleBnqo1uvGpIV7INfpR/+ZWe1svvYtDx4P6x3aU3equFr9mFRp/GNQYFSO1S0RiokifmFuHjYG+0Q=,iv:1JAWubkXxbsC8ua6xGO+ZlbVZ7ByFDx1W4+tA+cu3Bw=,tag:pRgAQAbvDt2EIrX0IZvlEw==,type:str]
    version: 3.13.3
