apiVersion: v1
kind: Secret
metadata:
    name: pihole-credentials
    namespace: network-services
type: Opaque
data:
    web-password: ENC[AES256_GCM,data:j+Z6WYQM7ElwWUI3bqUT2Q==,iv:MfsiZ71+/dmjYWhYHf2VvQ505SqwpMXhkXhkTrjGk5c=,tag:ksHt386uNTsmQDDtk1DhrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveWJubTFUNUw4WGhiOFNO
            T2J3R05oUUFYSGx5MHNnYzdQKzl0K2hvK0J3CmQxRmM3YzUrVG9MQWp5MVl0aWc0
            YWRWQWUxY3lFOFppSkNqeUR5S2lSNHMKLS0tIDk2SUtGcUg4UHM3V0tWRTVaVC95
            V0VxOVo1QmRiYXZ3OWszN3RuZmgyS1EKwmw7SV1/Ihyzv1h+0kif2fohI+ZpKoTX
            xbhi3xVFCQMX10VK4LGTpWmBTEq8xxJyAGTUAy919lgRI/zoeVKivw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qatpp7y6rrl248n739dsnh622jcncx49e4vnrusvdgx0un0t4uqpk40m5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T02:59:49Z"
    mac: ENC[AES256_GCM,data:Ru+7+yO6biDmYPsOaHEIlvD8mOETi8tLxlKNCVee7wUlnODsnhOxqhic3S1fD+OsUijGGa/xO2iR0nOu2gt7N0uezPE2WkiQY3ct934XZGXFhEYUG+zXXDuf/MUZX+byU5YGEMLL4kwhmvvv7EVQ7VEkXdKvlUZVvrb01tqc/ac=,iv:x0OalMmFjgn/a6hhHVRBSy12FrdgHcluvrQ0+wwFKD8=,tag:B0MRejsF7VyC0pMbBOha7Q==,type:str]
    version: 3.13.2
