apiVersion: v1
kind: Secret
metadata:
    name: pihole-credentials
    namespace: network-services
type: Opaque
data:
    web-password: ENC[AES256_GCM,data:d7ouAE8orhwYuas1szysFg==,iv:MfsiZ71+/dmjYWhYHf2VvQ505SqwpMXhkXhkTrjGk5c=,tag:kyuR5JZW3Z6BzZcoR/WGxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRTFmb0lQcGNoQmtmNGY0
            TGg5ZVU2NEZtcTd0eFVPL2dTNm5SRTlrOG13CkZTaW0rVGtneEtvVXZBcGZ1RmVi
            R1E0SHZmZlI4UEtaNmo3N2tIdUhocUEKLS0tIEVwRFlRZmcwUFBMdEVGbnhwZVdI
            aW1TZWJkS2FJY3FnbFdhNC83Zy9LckkKeUKD33/TmT7I4DvDf5FFv53SLKFU0uKV
            DZxw+7WYFs/Hy+lueYZ2Q6tEYRjZCOey/BOTodE8l8OxnVJhgwD6bA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T01:46:24Z"
    mac: ENC[AES256_GCM,data:+MWL8kGRVkbjHGUtW+7aXcro/LpVxp7ZQHitk3M5jaPDYYsD6Zzd7sTkafHBgSU7854eZe3UUZdGoFkPVYz1iJ3JmWHZ8O4Dwq+58bNOhYS39OlZX0ODAX5ZD41yjaI7JorYA+8ibUPF9QLn1B2DtPlgAk6VhBIEALIscU7ZN8Q=,iv:WSF0XH475RR3ZNVmr19g1nbROSD0//OYPnsoB/Fe6I0=,tag:mpBg+WkaMbzMCQccfudv2Q==,type:str]
    version: 3.13.2
