apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: network-services
  labels:
    app.kubernetes.io/name: pihole
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pihole
  ports:
    - name: http
      port: 8181
      targetPort: access-https
      appProtocol: https
      protocol: TCP
