services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.6
    container_name: jellyfin
    user: "1000:1000"
    expose:
      - "8096"
    ports:
      - '7359:7359/udp' # Client discovery (LAN)
      - '1900:1900/udp' # DLNA service (LAN)
    volumes:
      - ~/persistent/jellyfin/config:/config
      - ~/persistent/jellyfin/cache:/cache
      - type: bind
        source: ~/media/movies
        target: /media/movies
        read_only: true
      - type: bind
        source: ~/media/tv
        target: /media/tv
        read_only: true
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    networks:
      - home-server
    deploy:
      resources:
        limits:
          cpus: '3.0'
          memory: 4G

networks:
  home-server:
    external: true