apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:5FaTBv3UGWEABtiEA5svSHAy5QitybJ2o7WkNGjPmZfOgviOpj2yJCFvTdwEPiCYW8Zf3VBgf/8=,iv:7pUP1TGhuiC27n+p5Om/ALcA2eaLy67RTlpbfjuYG70=,tag:TydNupT1xLcS3bLLfgvfFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UFVnZnAzN2dvSGZZMGw0
            RVREQVZQbU1HU3BEWDMvVndXd3FhRytlVXhBCi9GVlUwYmhOblVxZFVHMTMvMGMv
            N3VNOFZGN0s5aUFMVjVCYUF3QTl4eUEKLS0tIDBpVUF1R05ZOUpXRmFCakt3elZr
            MDMrNkludWpMMjRDT1l4TXhsRk4xSmMKCcaNC8qmfOZDDZ+GicvH7Gv3VSuuEmMO
            K8LehAoEmMdxT4LIGVXsdEjkh1b6MTf0dFKjmE0eG7clBHpVDMrxIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T01:46:28Z"
    mac: ENC[AES256_GCM,data:Q2nPdjgVKUukbhjQxeEoJqRa7cB92G0w+OqrQd9mE0R+1uZcbNDIV2STzarYsCX6mjTchLaGJ4IDa3TxP+JXrr6nKFyuEKcUdYTVcmaoDnrRejr7n4puzl85Cy96daNYUVTWU8gYsGFBvf/z5Gh0JFeY8Rv/5jHKwaucgsvIAhk=,iv:HJtmo9ov0/oe0dFGgu8Q5dU+qEd4oSxIWqHjflmFjmc=,tag:UTnLqrhRSBo8/0hVgjFfJQ==,type:str]
    version: 3.13.2
