apiVersion: v1
kind: Secret
metadata:
    name: audiobookshelf-secrets
    namespace: media
type: Opaque
stringData:
    bootstrap-password: ENC[AES256_GCM,data:5G9VDKc/KhPe1gOyZb9rY8mtGHYH8v1nP/bmZaeqUv8/PtF83AAnBPys4TZwCwh2pxqGPAtHIM1W2Mp+0qxvFseKydv2dq9biXtBA72IrEVZjl6FXQI+7mFT0PNX5ml6,iv:gYhTSdc572WpeBghJAwExK6OLaJ9nZC+9t4DjbH35+c=,tag:fwfAnwsk3G6aPuF8SyHccw==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:KaGlRdrHPPEwJUQOa+6UQOBrmajCNWAOtDa0n2gScSAULGh7xgUcyvyI6C7IFkApcjsNRkU6t4WITeI2x4+uN8Gc5U86SUT+NFw7/C4D2jaNjVsInrwngDVYyp87slX9,iv:9YM31o8HsDHSeJvrsHNQBQ7taZVU932oDLe7ESRYpsU=,tag:H4rFZR6k+2IuqU00gnAmSA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQVl5c0QxT1kzeWVUdE1h
            ek91aWpHZmdDMmV4d1RUN2NZSDVoMnRISlRrCmxBaWlVMG4vSzBNbks0SkNrM2ZB
            R21OZ3ZDVUpTb29nZDhDQ1F5bjkwb00KLS0tIFhINlE0YXIybHhkQml6UExQVVlR
            V1hTYmdZM0puZVdZRXFvb3Yza0lndWMKFZo6SfyKiF9faI9vDHkF86eFUd3reArH
            Qk6I/UOglj00ysKHCrMvXn7mvQJQwYjO4LxrTcyjvs6INYMnqZxYdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-15T11:32:56Z"
    mac: ENC[AES256_GCM,data:NeT5nXSf6zKNZUS6pqaQiJO3ZdYxX/XFn9/nZ+oN9ER0b/awZEMppZRFM+ldgq+kuzeyoSAoyPeicZI7kWgaumFLyEKIPkHFPD/qRSHRF3HzNoeAsyKp4QnM2SnF/4spRMT/PGHt5vkFrzi/+5fV6dkaar1qFZRayb9mfS9vV8w=,iv:qQo9smZeH5u2R7yVrP9VvoCbOym1uRQS0xwZmtplg+8=,tag:0QE2kiHMQi+cePxjIiEH7w==,type:str]
    version: 3.13.2
