services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:2.7.6
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
      - ALLOW_INTERNAL_REQUESTS=true
    volumes:
      - ~/persistent/heimdall/config:/config
    networks:
      - home-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  home-server:
    external: true