services:
  radarr:
    image: linuxserver/radarr:6.2.1.10461-ls308
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - ~/persistent/radarr/config:/config
      - ~/media:/media
    network_mode: container:gluetun
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl -f http://localhost:7878/ping || exit 1
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M