services:
  radarr:
    image: linuxserver/radarr:6.0.4
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - ~/persistent/radarr/config:/config
      - ~/media:/media
    expose:
      - "7878"
    networks:
      - home-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

networks:
  home-server:
    external: true