services:
  loggifly:
    image: ghcr.io/clemcer/loggifly:v1.8.1
    container_name: loggifly
    restart: unless-stopped
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=America/Toronto
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ~/persistent/loggifly/config:/config
    networks:
      - home-server

networks:
  home-server:
    external: true
