apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.sops.yaml
  - pvc.yaml
  - access-proxy.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - route.yaml
configMapGenerator:
  - name: downloads-storage-guard
    namespace: media
    files:
      - storage-guard.sh
  - name: downloads-import-cleaner
    namespace: media
    files:
      - import-cleaner.sh
