apiVersion: v1
kind: Secret
metadata:
    name: media-vpn
    namespace: media
type: Opaque
data:
    wireguard-private-key: ENC[AES256_GCM,data:9e+tKjgu9GGkeddBqag4KytrKv8gBoy+KbutDDodXOU27vKXzwhUkuHpKVtHpTGLx/SU8qLVOHzmJ56I,iv:zsEKFIz048c4WPlJop90/yO3KfyJBtMzzww2QtGYgeo=,tag:/Xk7IGua1rKDrw+y9NKY4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNkpEMVZ6WnRBODhNTCtU
            SjV1L0xObHdXL1o1amRSQ1lYSWdISHJySXlFCnNqclJWc05pSHRVQng4amgzN3JZ
            WU0rVEcvN1Q5aEFNcTAzejQxSk9mcVEKLS0tIHJkS09UaklHNkpCVXVYTEwvdFF2
            Sk1OLzdQZVE4Yk5WL2hsNG5oVDJGZ2cK5Jh/FbLCaIR9Tvg72AghTAxv2scv3sLo
            fVhmciBTRN362TEu59su98cV3Ldpn19njxlPc/dqhzSAOTdAf7lAZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qatpp7y6rrl248n739dsnh622jcncx49e4vnrusvdgx0un0t4uqpk40m5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T01:02:19Z"
    mac: ENC[AES256_GCM,data:OGvy1bHcTlBmzBHLVqavoJNcht9bJz3VctHtZ+jvSydgIXhQR9GVv7VylO7pCl3Yb24PR0UyK9nY2+1X2wxZXNPNB1bzyuasPI4rXP0546vDJQyhP663RXliDIEy7TSCSPycxLuuyX2XHG9sGBaNpwPHwcO0pn4L/hejlRpCQVg=,iv:4/F2L+1kghRYqkf9J3FtpnoXC7EbtHkmi3jg/bo1dw4=,tag:nXstLrggqzu7UsTEccCBFA==,type:str]
    version: 3.13.2
