apiVersion: v1
kind: Secret
metadata:
    name: media-vpn
    namespace: media
type: Opaque
data:
    wireguard-private-key: ENC[AES256_GCM,data:v/lbis0aj7bq7y452UsNlojU0gDL9nlc9fxuwRt9vMAF6QGvjUkeF6cAXwJIorl31t+VWfqeBEAqTkCs,iv:zsEKFIz048c4WPlJop90/yO3KfyJBtMzzww2QtGYgeo=,tag:x1lc8jzzOiLemAAohQG2qA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTVlrRDhBYjhWZml6VWd3
            NWxoNlBWZHRkaUlqNmRMeHNjZmNQOWJmTndnCkxRNVJnc29oZGFxN1phRW1BbWox
            Wi9tRHQxWmRHV0VTeHMrRkpuUXRBd0kKLS0tIGk5Yi9hSFlSc3E3VUJvRVdsdzBv
            Y01HSGpEcUJNTktsMnVTL2V0NzNNM2sK6P2i7eV0gvApuz/D5aRL5l7ty9LfezhG
            yB81G1GdZG5+MD8qkH8dJkq4GnVORsY0jz+KiPCGECxIlDRFqz3IXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T01:46:17Z"
    mac: ENC[AES256_GCM,data:HX0WstMyAI6ID2YS4qgw8eKPHRTGZHG9yoioh/uYANByPmGX6KUgE+uaI/pdwGA/vTyK3gFj9y1Y9p+G22R0nkX5xesezDT8HSKLp/Vx7dkISxLuHyUwCxargR76ScQJpBxwPJO1Y+aMPkSxCziBwxaOazkICZDpeF8UXPHQGZw=,iv:EPvTU5wOC0N/b9+fSAx5J4eWqDcwxUUh77L3lEFCSno=,tag:ItxptF7ea3sCZ/R5ax1QXA==,type:str]
    version: 3.13.2
