apiVersion: v1
kind: Secret
metadata:
    name: argilla-secrets
    namespace: apps
type: Opaque
data:
    password: ENC[AES256_GCM,data:C6M4pWdCGUbHKged,iv:HKgIHIzAbu33R26mc/t0Q3ElowKx6t+JODfzu/xMqyQ=,tag:atKGGe1+rC4tR54P/HF1Ig==,type:str]
    api-key: ENC[AES256_GCM,data:SHFW5UbXMuNe7l53ixQrrf1DT/qlTTEuF9rxOWzSHfAxeSaNtOiBXiTmPshBqEyXoIRNw3FOqwWEpYsUTZ5voNNTdY5nB4ehjKB6TC5Trkow2PPQi5sPOg==,iv:Lj6HTtE8K8bHp0fDwYBmAAgpHWPE2eVxCk2cCm3zopE=,tag:26WS4LeWMcEnzkfMJi9VTg==,type:str]
    postgres-password: ENC[AES256_GCM,data:l8v8yoozpcCLgV93kpAYG75PwnslG49olj0XPA==,iv:hrpZaKbeykmNiEE+CXbsKq0VSx69ADTWWuhgIzLtifs=,tag:iBQAxL6SOWhZKlT18ldlew==,type:str]
    database-url: ENC[AES256_GCM,data:CXj3G1k3vpAFplbvQ9HtWNe/Xw/CU2030bRJm2ljkbkvh05dpTxwNZg3sTf3RhRtcbd2Cm8Mw3ihgmnB7/4amSQV3VUyNnvexlx6VO2hgyjbQk7W4GtnQKrBFS6SOvfQwGxMlS8x8iqEymEm,iv:QPCD0UWpUoG9nX7zSKl3Rzt11JqstI3qwPb9bkqghag=,tag:NmH/ua0ypIYRppAunXRccA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSWYwL091cXVRdmw3NGFp
            K1J0aDFqQ29jcVhFbE5YS3VGdXBSTjZRYVhRCnUzc2lvZ2owcjNCcE5SemZPeTln
            Ykt2RXRyL0UyT0NyUkdvektwR1NKa0kKLS0tIGxSbFFvZnlNWGs3R21INS9GalRK
            MGJKVk8xMjZVWDVXdk4rUDhTT3pwV00K7wYPi3whDZoV+X0dums6FqB97ROLnM3O
            7JGquiPyK54GZza98fG+MjfPc6m8IqF8Bybqj0n8sn9Vw2cPxkNYow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T01:46:13Z"
    mac: ENC[AES256_GCM,data:bzpSLpdnhAErbgdOXsDTakr+/G3DXdI1VkZCRYDBpi5lO3On8xlms9oUI/j7rVtCg7Oth+BiQ2VbOE49qccGMdsjiRjG2Ny9FKARjyWuVXaqvS5aKobNf0SQLVdW+3BwiJMrTS4aFIub8MxW0XfZKtBKc8asR63cU5LAqDt7qos=,iv:lU9UnJ33vhz5hO1S8YZVFN4AauU9rmDvM4K1sYWdU9M=,tag:dX+xybr9BDDRdFDblhRfLA==,type:str]
    version: 3.13.2
