apiVersion: v1
kind: Secret
metadata:
    name: argilla-secrets
    namespace: apps
type: Opaque
data:
    password: ENC[AES256_GCM,data:Zei/46hlkP/meoe1,iv:HKgIHIzAbu33R26mc/t0Q3ElowKx6t+JODfzu/xMqyQ=,tag:AHFlj9S2mJC26gt6anPH7Q==,type:str]
    api-key: ENC[AES256_GCM,data:s+eJufufqX1IKOaJBjxWlydxJJVws7tfxEo5Y0ev0gscfzZ04YPSNcmhMhC2okduUglU/r2lLBtjAwBRhhn9P/XR7iexpbtm27mFg+TanY3j83DtIlHe1Q==,iv:Lj6HTtE8K8bHp0fDwYBmAAgpHWPE2eVxCk2cCm3zopE=,tag:dPxmIe2bruTU1x8iyauidw==,type:str]
    postgres-password: ENC[AES256_GCM,data:AqTfWeDxLtfha/IQL4F8EVJux0NPjc64dfqyrQ==,iv:hrpZaKbeykmNiEE+CXbsKq0VSx69ADTWWuhgIzLtifs=,tag:WXrrFEpghf7klBqhAFsvJA==,type:str]
    database-url: ENC[AES256_GCM,data:SFcnqRgp6OrxJpzwcuUlgbwL7CwHhM9RvkHsrWAY8iKxfYvhQhh1ZdhYO7kRV3ZZPaqa4qgAzf9+oBOTKF6bBWKgqNX4C9d8BfpF8/j5A5iHhfCd9/8lyRxvpAGC0EUyfh8PdHM3WxoVYyh2,iv:QPCD0UWpUoG9nX7zSKl3Rzt11JqstI3qwPb9bkqghag=,tag:Dt+PtOQUVmDvBTrrlZa3cQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3enVsR0thVUt5bVBGeDUz
            TWJlQ0w2Nnoxa1pvLzI5Q3BqRFp6TFZkbVFBCk95WnRKMGtLdkFscTQzcE5QTW1y
            Yi9BRjU4QlRoUGdIWm1jYWQ4T3oxTzgKLS0tIDhWZS9jUUJPc2h0NVpiUk9nUTRI
            OFB6eHNrN3FzbC9OZ2tKQjZDOGU2OEUKlh7rBviuCRx+48fodm7xolKJs6DHRbj7
            af4HSdOsbjs1pAAOii2Uv0dTe8qSytphYdRkGJ6jZQb98U7H0Oafag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qatpp7y6rrl248n739dsnh622jcncx49e4vnrusvdgx0un0t4uqpk40m5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T00:36:55Z"
    mac: ENC[AES256_GCM,data:wSq4BxsVouL53Wu2OrbncL3Q9dOpppI6/hlhQW8cD2NxCYEklW5vPCRelR6tzet1TZgCCsSr3o0wRDUrl1KR9dLtaMo976BXH82UMX6NDRA/ukTP29HJt4xOxdkJ5pK3anABjpC24JpMW6pPsSqfIq60z3WGr09WIf31dIX6RBM=,iv:dqsSs+RbckrycQdaYGiVVic2MSbALdHor5cWecFxh/4=,tag:zI8v5hfp/buhjMOtGj/Hrw==,type:str]
    version: 3.13.2
