apiVersion: v1
kind: Service
metadata:
  name: argilla
  namespace: apps
spec:
  selector:
    app.kubernetes.io/name: argilla
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 6900
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: argilla-postgres
  namespace: apps
spec:
  selector:
    app.kubernetes.io/name: argilla
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: argilla-elasticsearch
  namespace: apps
spec:
  selector:
    app.kubernetes.io/name: argilla
    app.kubernetes.io/component: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: argilla-redis
  namespace: apps
spec:
  selector:
    app.kubernetes.io/name: argilla
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
