apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage.yaml
  - backend-mtls.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - route.yaml
configMapGenerator:
  - name: syncthing-access-proxy
    namespace: network-services
    files:
      - nginx.conf
