apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-data
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-media
  mountOptions:
    - hard
    - noatime
  nfs:
    server: 192.168.1.2
    path: /home/reza/persistent/syncthing/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data
  namespace: network-services
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-media
  volumeName: syncthing-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config
  namespace: network-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
