services:
  prowlarr:
    image: linuxserver/prowlarr:2.3.0
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
    volumes:
      - ~/persistent/prowlarr/config:/config
    expose:
      - "9696"
    networks:
      - home-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  home-server:
    external: true