apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omnifin-data
  namespace: apps
  labels:
    home-server.reza.network/retention: omnifin-retirement
  annotations:
    home-server.reza.network/review-after: "2026-12-01"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
