apiVersion: v1
kind: Secret
metadata:
    name: omnifin-secrets
    namespace: apps
type: Opaque
stringData:
    encryption-key: ENC[AES256_GCM,data:5V3rAX4zWJrajBrmmyFHi1NI1gy/Unu5JDHRlBwEL6RfzCgezD33A0KfTEE=,iv:G7fxD7VBaGkdW8Uy5SRCcO78YPIin97wuRXzt1dac+g=,tag:vNjshErID4VhfuHtf23CPw==,type:str]
    recovery-secret: ENC[AES256_GCM,data:5ngZgkJH3s/xL645n4I0mFtMBVUTpi5CTTuq6lR4U8XF72HdkT4Dsw7xKWE8eswtNYZaZIyNBOXQ2I4dqWJjAA==,iv:F+KLo6eCuhgpyrHfm3Q5+wMl+yHO08un+WN5m17+v48=,tag:Rob/YmB5pV3lPYBYSNcRUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMXVGYVIvYnhpUS9wNVFS
            SGdsaUV3am5NZUEwR2NCbmJEcGh0TkdZd2pFCkpYbVJzcEsyTFNEb0o1Z1V6RXhr
            YkRhNVlNYXNGUGZXUDBDQW5hdnExbGsKLS0tIHFiY3FDcUxlSm90d0pnNFZJTzUz
            M0FSTFFVVVh2SFRXNWxhYWl3Mml4dVkKoi9fXunifkv+G78/Bxn/yfoSR1QMbZXI
            atJIyurFbaZsPo/QVYHrXgEq5XMbWzmaTgzZRtKQe5GhPXcC4OKwcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T04:56:21Z"
    mac: ENC[AES256_GCM,data:QG9JJFwv1CfWLIYvVEMuwzEY9+jq48bbE82NkDg6cW7Z+T4va3KBehIBQvu9sXgztqcdqqQWEGQ3bxG6/cT4eYKo6z3QXIqKb+WFnnxF5ZrzEt0boXqW6l8epSgOzlAVPeBcyq40znxht9mqMSWFYiLUgRCY9b9e3/Tn0JrucjE=,iv:ltnOALjWkhw9YzrO4NcpwrDH1F/evkafKmahT5dj/XY=,tag:fYnM1DJUQ8yAF4zuyY9KOw==,type:str]
    version: 3.13.3
