apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - ../../infrastructure/namespaces
  - ../../infrastructure/coredns
  - ../../infrastructure/snapshot-controller
  - ../../infrastructure/longhorn
  - ../../infrastructure/juicefs
  - ../../infrastructure/metallb
  - ../../infrastructure/gateway-api
  - ../../infrastructure/traefik
  - ../../infrastructure/cert-manager
  - ../../infrastructure/observability
  - ../../infrastructure/nfs-media
  - ../../infrastructure/dri-device-plugin
  - ../../apps/homepage
  - ../../apps/home-assistant
  - ../../apps/actual-budget
  - ../../apps/finance-display
  - ../../apps/cyd-ota
  - ../../apps/authentik
  - ../../apps/seerr
  - ../../apps/omnifin
  - ../../apps/navidrome
  - ../../apps/mcphub
  - ../../apps/hermes-agent
  - ../../apps/open-webui
  - ../../apps/vikunja
  - ../../apps/speedtest-tracker
  - ../../apps/argilla
  - ../../apps/audiobookshelf
  - ../../apps/calibre-web
  - ../../apps/cloudflare-ddns
  - ../../apps/downloads
  - ../../apps/sabnzbd
  - ../../apps/cleanuparr
  - ../../apps/prowlarr
  - ../../apps/radarr
  - ../../apps/sonarr
  - ../../apps/lidarr
  - ../../apps/soulseek
  - ../../apps/blocky
  - ../../apps/kea
  - ../../apps/stork
  - ../../apps/samba
  - ../../apps/syncthing
  - ../../apps/vpn
  - ../../apps/jellyfin
  - ../../apps/duplicati
  - ../../apps/headlamp
  - ../../apps/loggifly
  - ../../apps/maintainerr
  - ../../apps/maintainerr-tmdb-proxy
