apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - ../../infrastructure/namespaces
  - ../../infrastructure/longhorn
  - ../../infrastructure/metallb
  - ../../infrastructure/gateway-api
  - ../../infrastructure/traefik
  - ../../infrastructure/cert-manager
  - ../../apps/heimdall
