apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - ../../infrastructure/namespaces
  - ../../infrastructure/snapshot-controller
  - ../../infrastructure/longhorn
  - ../../infrastructure/metallb
  - ../../infrastructure/gateway-api
  - ../../infrastructure/traefik
  - ../../infrastructure/cert-manager
  - ../../infrastructure/observability
  - ../../infrastructure/nfs-media
  - ../../apps/heimdall
  - ../../apps/home-assistant
  - ../../apps/actual-budget
  - ../../apps/authentik
  - ../../apps/jellyseerr
  - ../../apps/mcphub
  - ../../apps/open-webui
  - ../../apps/speedtest-tracker
  - ../../apps/argilla
  - ../../apps/audiobookshelf
  - ../../apps/calibre-web
  - ../../apps/cloudflare-ddns
  - ../../apps/downloads
  - ../../apps/prowlarr
  - ../../apps/radarr
  - ../../apps/sonarr
  - ../../apps/pihole
  - ../../apps/samba
  - ../../apps/syncthing
  - ../../apps/vpn
  - ../../apps/jellyfin
  - ../../apps/duplicati
  - ../../apps/headlamp
  - ../../apps/loggifly
