services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2026.02.0
    network_mode: host
    cap_add:
      - NET_ADMIN # Required to broadcast DHCP
    environment:
      TZ: 'EST'
      FTLCONF_webserver_api_password: '${PIHOLE_PASSWORD}'
      # Allows Pi-hole to respond to queries from local network
      FTLCONF_dns_listeningMode: 'ALL'
      FTLCONF_webserver_port: '8181'

    volumes:
      # Persist Pi-hole's databases and config
      - '~/persistent/pihole/etc-pihole:/etc/pihole'
      
    restart: unless-stopped
    
    networks:
      - home-server
      
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
