apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: heimdall
  namespace: apps
spec:
  parentRefs:
    - name: home
      namespace: traefik
  hostnames:
    - homepage.reza.network
  rules:
    - filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: custom-errors
      backendRefs:
        - name: heimdall
          port: 80
