server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name chat.*;

    include /config/nginx/ssl.conf;
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;

    client_max_body_size 0;

    error_page 403 /403.html;
    location = /403.html {
        root /config/www;
        internal;
    }

    location / {
        set $upstream_app open-webui;
        set $upstream_port 8080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        # Disable buffering - required for LLM streaming responses
        proxy_buffering off;
    }
}
