server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name mcphub.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 25m;

    error_page 403 /403.html;
    location = /403.html {
        root /config/www;
        internal;
    }

    # Enable websocket connections for Server-Sent Events / MCP HTTP
    location ~* ^/mcp/(.*) {
        allow 192.168.1.0/24;
        allow 10.8.0.0/24;
        allow 172.16.0.0/12;
        deny all;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app mcphub;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        # Disable buffering for SSE (Server-Sent Events)
        proxy_buffering off;
        proxy_cache off;
    }

    location / {
        # Restrict access to Local LAN and VPN only
        allow 192.168.1.0/24;
        allow 10.8.0.0/24;
        allow 172.16.0.0/12;
        deny all;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app mcphub;
        set $upstream_port 3000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
