server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name sonarr.*;

    include /config/nginx/ssl.conf;
    client_max_body_size 0;

    location / {
        # Restrict access to Local LAN and VPN only
        allow 192.168.2.0/24;
        allow 10.8.0.0/24;
        allow 172.16.0.0/12;
        deny all;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;

        set $upstream_app sonarr;
        set $upstream_port 8989;
        set $upstream_proto http;

        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
