apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
configMapGenerator:
  - name: open-webui-searxng-config
    files:
      - fallback-settings.yml=config/searxng-fallback-settings.yml
      - search-provider-proxy.py=config/search_provider_proxy.py
resources:
  - secrets.sops.yaml
  - searxng-secrets.sops.yaml
  - searxng-provider-secrets.sops.yaml
  - pvc.yaml
  - deployments.yaml
  - services.yaml
  - networkpolicy.yaml
  - route.yaml
