apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
configMapGenerator:
  - name: open-webui-security-policy
    files:
      - reconcile.py=config/reconcile.py
resources:
  - secrets.sops.yaml
  - pvc.yaml
  - deployments.yaml
  - services.yaml
  - networkpolicy.yaml
  - route.yaml
