apiVersion: v1
kind: Secret
metadata:
    name: open-terminal-secrets
    namespace: apps
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:eX2SmKHwLBor3Fy/EBrUE7D/PPmsk2UCorZzNXG6SXSGKxeY8rbEmtXRylbxdnsAztoO67QRSaDZ+iKLnyt9uQ==,iv:HCv8F/HIDSic0QCrqsHx18DebMXGOROpEmku9PhP1yY=,tag:gCiFJfuDd48AUXtdeZfFkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTmFzTUdUbGorUjR3UVox
            anBSbGxpNmZUcWRYaDluR0M2UzlFVzhHdFNNCmlqWTVtSTVOS1cwYUFXckZOeFM0
            NWljNE1KNG9xd0plcFZtSWVvVVV1RkUKLS0tIDJMb1FyYkVlMGZOUFE0czdPWnlB
            NjNmRlBTeVBoaCtOMlN0UG1YME9zeEkKzBGU60n7REMbe19igpnlvmj5pZ00yCtY
            Tghhypvchra8+M29AW7NCwVvDN4ZsjuFaZS9ABofdeebt4xs/Ws2Ew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-31T04:16:23Z"
    mac: ENC[AES256_GCM,data:tpsh8pbX8jWEZXFyQntlK3jrPGQ6L2ry0zW6Ai6U0bjkYGM1K24FhBsDJ3ByUmvt9FviU/QCg0Q3GuKCxKlJ0qbxw6VXv4+uWMY69MCUTZB7eGMLWgzyUdfsVwDgsfiW3KfvEj2nInLXbLrMl0z6jBfIVJuMAyVWReGotm7Oq38=,iv:8Th4whmnmYLder+JBd0WG55LMhWjeHzxRWqJABo32Js=,tag:qAYZRFlrw3d+uuqcoXdqKw==,type:str]
    version: 3.13.3
