apiVersion: v1
kind: Secret
metadata:
    name: searxng-provider-secrets
    namespace: apps
type: Opaque
stringData:
    brave-api-key: ENC[AES256_GCM,data:tbhyNomM9D5ZxH1z2B8z4NVRBPO7GP0Ivj/Hd0hfMA==,iv:vN8BnLijYPZ+5CPbBB4Xdskeyinlb+TRYNjSXBXVCkU=,tag:kfg0A2z4D70J5u5g+WZViA==,type:str]
    serpapi-api-key: ENC[AES256_GCM,data:+mz7+v/vO+eFIO/o53sbJNy2P+fiIfzS9sPvfmpiVJW0kLoyZmkPruVLE5l0XJxApnYueZxaEEvjvyDgVfrnOw==,iv:D0ekx7VtNy6ky/PEep5CiigbpBjP8LPzzDmxrHdrl4k=,tag:bhZfSN1KAPVYy9bVYL0alg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeS9meFBRQmVhNW95Njht
            SXdJQ2twd2JIb2JBUWtlem96OCt6VlV5UlVvCk5uZC9TU3BsZGVXdkI3TW9SQmZj
            L2ZMUzhCNEFTNmdZODRlVnJmWEFVd2MKLS0tIGJZUCtLcmpjMFBSc2ZobnV5SWV3
            THo3R29iSlNackRkRzFqT0xabitTek0KugBSvkIurPRIJhGgbxZPPgDYIx+1cTca
            +ykQDRCzecF6MhQJBp5WZxlLZhNNGdvluqfB+2W5AKV8OL++7UrQyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-21T00:37:21Z"
    mac: ENC[AES256_GCM,data:BMTy62X9ngLGve9ZrHr3d2uFwKxZICQ/tVj/JqsSPbvp6e1LTrPEFtQ9XITqLEtK1uDuEuk4lpOcE7PcljZ0Q95ddsViDpRqWTIsCdCodh65TzhI/KBXnMxqL3GlMcUucPz9rLVRftLawshSEwkSTk4Ey2ldYfaiNIw7Yt7xYgI=,iv:fzcyupkW39iylBx+BsWasj/iw5RpHbR/lp3NHxaGw/A=,tag:6XZKvCk2KKPSZaqe0md01g==,type:str]
    version: 3.13.2
