apiVersion: v1
kind: Secret
metadata:
    name: open-webui-searxng-secrets
    namespace: apps
type: Opaque
data:
    searxng-secret-key: ENC[AES256_GCM,data:NdtnMD4/UE+uJB5hP1zNbSqbpFL38ocLIhQRRKzE3agWb554+1Z7kRBGKd4keDCz3p+tcClyVqS8zRi+bGOHdcQGV0sNZ5aQ0G65h6FwDYi0Jpp0Bsnu6A==,iv:uSrLkFpRt55KYSo96Pbesu3hmJuf17HasahxFXjAnEY=,tag:kkKt1CN9ohOy4ZrJW4BprQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUlI4K1dXajZwVjlLQ2p6
            RWNKU1E4WG1OWlNOdE1mMG52VnNTRStwb1NNCmFHNUxlblpibGFsYnZINHQ0b1NG
            MW9zKzE1S1RORWRBMXpZeit4cWVXaEkKLS0tIDdweUM4S3k0Y2N4Nmc3bWZHR3B4
            WkdqcnNNRkNEeHBMUkRwL0cxenNkY2sK6vklk88CpbbSZvQ7o62ku24KUYD7CCAS
            JyJDfyRXVRrK9uPGO+IKl58VbhV7v9a3ESpyPk2iAoVvmmyyQNYKsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T17:24:11Z"
    mac: ENC[AES256_GCM,data:hKA+c7J9dhBLsHOeXUD8QD/hlM4HO6bIvTtCvZ/BK8HdhwKOyPvs+fwsxgqSbvuhq4tWA9Q//sNseAnnNooElM2HLB6UhDVetkRCvk0koQmBLBkWq/Hfi8Vj1eRhp7Z5QsGhJL+cReQTpsSR0iCEUzDza895KN0nqAyir1q8dYg=,iv:i1LXwLbmSFc7Qsq+ekOi5OBwXcbt4nlgpNYld1ZXK/U=,tag:AGpPG/zZLfnqCqqwfth3Mw==,type:str]
    version: 3.13.2
