apiVersion: v1
kind: Secret
metadata:
    name: open-webui-searxng-secrets
    namespace: apps
type: Opaque
data:
    searxng-secret-key: ENC[AES256_GCM,data:ecyLVkOFONl0n7bx575rn4lQoii8mgK1bzWxwJvmS+T6rvOBlLMl19B0tb2IqQM7VUvWc68kfddSddG/a9VEmekR+ciXk69j4sXMrDm7/tSxKwr5pK5ukQ==,iv:TrIiFujvq0KrpkGFnCbMoK3NnMraG066WUkoPsWSz1U=,tag:wQHjx97fko+gQ5B+/rGaUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUlI4K1dXajZwVjlLQ2p6
            RWNKU1E4WG1OWlNOdE1mMG52VnNTRStwb1NNCmFHNUxlblpibGFsYnZINHQ0b1NG
            MW9zKzE1S1RORWRBMXpZeit4cWVXaEkKLS0tIDdweUM4S3k0Y2N4Nmc3bWZHR3B4
            WkdqcnNNRkNEeHBMUkRwL0cxenNkY2sK6vklk88CpbbSZvQ7o62ku24KUYD7CCAS
            JyJDfyRXVRrK9uPGO+IKl58VbhV7v9a3ESpyPk2iAoVvmmyyQNYKsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-20T17:06:52Z"
    mac: ENC[AES256_GCM,data:mLBeGoUza73eGeto56n+nq+/TeP/Qf3EEGGmw6Bd9RYrHWuHCySxMzLazTA3sLbz2egBtVQ3HTR6g5FgUPQK9wji8zsNy8RRLwwezNbtO0Zbf9f4CiQrQikE73YgGhBC7w/qMbH7b1fXchCZ2QHSbCV/X8BHLiG2EtRHRdDk2zw=,iv:n+2OGlH8o2K2y0P9vCNzx7j24+NC2HG62nMPFvEPE2U=,tag:v2lF0sFpbv2YSXI83GIOPw==,type:str]
    version: 3.13.2
