apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secrets
    namespace: apps
type: Opaque
data:
    webui-secret-key: ENC[AES256_GCM,data:uAz8nPN8IlR6R/0eO+Y2uCWzuk97TOH56YWfx0YqJwx8SPlIwvTEx3uU1gZ/AYl2YGqIbGL7W5SQK2U09WeyKZc3Qa4UWyJFeNYlxvQyPcfoy6yxdjkACg==,iv:KI8iwaCgrjYmgTbOkDIqyXLN0eCJ5d0BUHgQCmyrFp4=,tag:W3SJY1dOsrQ0Dy3QYQRb4w==,type:str]
    oauth-client-id: ENC[AES256_GCM,data:Zix2cF2M84Qt32R8BsSqIHmn5ID5OFxYTIWQb9OYkQxgN3YcraCGUt1OAg9VgKkp,iv:lpAbkyS3lWZAhl1/lc6Vlh5/4bOK3+VVngbhNRcBvRk=,tag:7RkKaUlUMxJQ4wpOu1j4Dw==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:ElKIcva4hzLzMNfBBtH//S0rRqGTE0VNNldnp5pGpnlt8pUVPFgQcu8vAN6QYByybVqvvaxkKoPuzxVY3+PeDSSXyFykZAQ+6NipV440XWEWOCr6dWFFow==,iv:cFdp2JFxiLDYupwuQRHpKZCimDH1IOYWw/nrUdzXHEk=,tag:Tk0fhAyMkPsb3yiLMWdA3A==,type:str]
    oauth-allowed-roles: ENC[AES256_GCM,data:3l5msPm2Mr4Effws851WjSjwlViWht1fZ9O56iETn+qhWYBzJGWuAUEHAQbKLa8giMFHLtMPOTDFfJ5cnFZhQpjNANgSRtDm,iv:CDDxqDj8PZ+3btC+v/ScQwtgdj6wD0dCTxPgtyT70pk=,tag:PADBu24Bc/eFpRZvbY3Y7Q==,type:str]
    oauth-admin-roles: ENC[AES256_GCM,data:+H8PtisExV7VlyxVGE6MQNUILzr3Y3H0G41tC4dy0NlsZRjSSrQ7mMUrZlns/vM/,iv:9YmnVTLzIS8q8P+XrhOl0UCWcMrvcVyUyN2N96YSjp0=,tag:KLN3wiyPnC3yrsL9NxR0lg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4M0Q5bm9VR015NE9MYzhs
            cnVXZ0NMUUcxaGpPVjFvQ21xbm1FempoZlh3Cnc1UWlKWGRrTHN3ekFmQ2RLNUsw
            SlFSRkw4VGpXNFlPNkVteWN0V3hTRG8KLS0tIGhXaTZWYXU5TmczRXpqRFBLNEJa
            QTJNZ2Y2eXJrZjlDWkpZSlNLY3RiRjQKBY6qr5zV8TpkNnsV9egVkOjVKxOr9gKu
            nygZ/4qBNZPswIb9/Ov9VWC5LtcfvkHfM+B90HDZqbCXcDI5IyRZFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10qatpp7y6rrl248n739dsnh622jcncx49e4vnrusvdgx0un0t4uqpk40m5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-13T00:33:01Z"
    mac: ENC[AES256_GCM,data:H6LXLtViBdnlXML3DwMC6r8IUYf0U4+4XmFTLEpi0wkhmRZHEHLeV5Gc3MUsyew5pKuhdYPqZVnZAVjbgqc0467WzCXq5xzmAXRtvFj2Nm7px1yy/eVDCSLvkyM2BCu+yX4pN2K/EXqU5z65ryK+FcqyWXg3kqnFzJmlFngh6Nw=,iv:nNSxL687BZrCpu7yhpoYy1DUKFkBfReVMfRRO6x9bT4=,tag:1aPgRs7E0Er/vgGedBR5Ig==,type:str]
    version: 3.13.2
