apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secrets
    namespace: apps
type: Opaque
data:
    webui-secret-key: ENC[AES256_GCM,data:OBdRVKvPpcvT2pn1WI7NkI2W1Q8uWRzV0l5HwlNwxiIe3HUoyBP3cJhZVXL5FTlQJe7Xh3tHGlcf5wjuo0e+kl08pIIwhjpRECXpaVn2c0oabWE4PlkBOg==,iv:KI8iwaCgrjYmgTbOkDIqyXLN0eCJ5d0BUHgQCmyrFp4=,tag:yKE5mpIwIC5jRSOAD2Ffaw==,type:str]
    oauth-client-id: ENC[AES256_GCM,data:OJzq74R1SZ0Vv+DKNbk314zcf/KEhl05z62xxuqIqGrjfXMVqOD2yx7fYnBGC4pF,iv:lpAbkyS3lWZAhl1/lc6Vlh5/4bOK3+VVngbhNRcBvRk=,tag:SiaZKi81rt7bHdGDaQwTlA==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:ze9SXY+S3rqAUuD/RYqyKro27fVfBRr2OrABmy1S3wGFH6eg68zEcVTNv0Pu5M8DS6ZJYs23q4Ov2eOFuL4rqW0B4JcU3CeF6T/f5rju/kpFoLeO2fVliA==,iv:cFdp2JFxiLDYupwuQRHpKZCimDH1IOYWw/nrUdzXHEk=,tag:/V/MR3NZsOgBFBZGrfAP7w==,type:str]
    oauth-allowed-roles: ENC[AES256_GCM,data:yn9k8XKWBg+mAVg3LemaWlQirhnYpem7t/TKAHJWcBnWKrdqmNAW7Lyd3qdveMosvaYRH0PSUx6JF1rtDgGkS1KV5e+HKnut,iv:CDDxqDj8PZ+3btC+v/ScQwtgdj6wD0dCTxPgtyT70pk=,tag:lwv8c9xKo/eO0MvGfpoPLw==,type:str]
    oauth-admin-roles: ENC[AES256_GCM,data:5y+PWPAHzw1KpdZJPNF2GyYCxMI8+aSVNlccBLUFxNBtJjtlXzGYjlPP2mAu2Iso,iv:9YmnVTLzIS8q8P+XrhOl0UCWcMrvcVyUyN2N96YSjp0=,tag:xlLgpMa/Hi0iILDh2iSY2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcDg1UVNReWk4RFhod3RH
            V1Z2RCs0Y3hISDRKa2xJZmt5ZlpOQ3hNZzNBClVzMVY0eVRrcSswUGUzQjF1dFUw
            eERwdm9BMzZuOWE0Sk5jM0VtR1J3dlEKLS0tIFo0U0V3RithNnVMVit5VEJtYjV6
            SnhBOFhEWUxkM0RGSk5EWXFsaU5EQmsK9NMqOnLRnBJp01f9B6z2aWetgyf6iITm
            KXqUhJFFbDRhW+iJ/7Sh+V7nGtq26c1hgLR/8zTf5qhzMRNOQMdLjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T01:46:23Z"
    mac: ENC[AES256_GCM,data:owp3TqKyEnJkuoUYdesLBQsDjGJC5kRhXk4B6W2DCC116LDKnD2bfdgFvT7w4wM+tkXBQYukvBff8Q+eja8aKgUWKbDDHPYNcuGDOVAS2MTEw2rzqBEIbIlzDZoRbKi583fjMVo9BOQ7LsCzxnx5JIQZ2vX0mHVVGE6DX6ayYw0=,iv:QaEEubqOXXWnzxV2pVKNpiypCXXkWHTOqsZMQBWQGBY=,tag:LHCkfVPSkmA4WjoWasC7oQ==,type:str]
    version: 3.13.2
