apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: apps
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/component: application
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/component: application
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tika
  namespace: apps
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/component: tika
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/component: tika
  ports:
    - name: http
      port: 9998
      targetPort: http
      protocol: TCP
