apiVersion: v1
kind: Secret
metadata:
    name: actual-horizon-secrets
    namespace: apps
stringData:
    actual-budget-id: ENC[AES256_GCM,data:if9Tqk716p5CAgTztAjWiySzVyVeLtKsZSKn0YKYq3ycNWf0,iv:haJzK+eQ04z36Ac5an8XAN09GfB3/aXfJ0UqNHu7Yp0=,tag:AS5CncQnn2JZgcc6xGAE2g==,type:str]
    actual-password: ENC[AES256_GCM,data:+A2QFwWHdAKvLtONL6c4+x/gLx3WMtahwctsBj8DpwQma8P9SKvJquv1o/i/LH9liqyjl5ISuRZUSTCP2SclJg==,iv:c/8Y357MRmcMYXnV4AShCOgbO/gYTPVmfUiulUfIwx8=,tag:k0QJrTDqgIK+pMK0sNtFug==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Tmx6WGpYRmxaaDJsSklC
            Tm1KcUJtM0ZLOE56b2RjR09kckZWcTE2a0Q4Cml3TUdpRmNvZ0pRclI0VThKRkgw
            aG15c0pUSlM3YTdEYmdxSGlHTHZnSUkKLS0tIFQ3QlNlWkdyaGxkN0dPWnN6Z3B1
            cVQ4SDdib0REZkx1ekxHMDlFT1VEWE0KmecJTj1zncMziqfBw8wlyZ3KwFLhELiX
            yROexgNzoW+VwR4wuLtvqfgGNUNj9RDLRl2aVVlaVMraqd+E4plZtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T23:17:28Z"
    mac: ENC[AES256_GCM,data:6MTdMUnR/iAUC8TifC8hP4E6wYmdvCie4+ITa16MI+tSIa8ow9K4H6BuG1w/z0jpqP2MW+Jhhy9RSTaMXd++/Xx2soAgx8M1H6nSly0xL+Cz2W2U21Sol0pq6gLM9hRYLYYbRsr9EzqL2jjkzxhBpZUWwDgt9b/zyd1wdgfEubk=,iv:ptTEUsn8p3F1i5T0KO/U1LeMywI9rTA++yvZlbLZO5M=,tag:ZZt16LGp88IVfKvJIjngeg==,type:str]
    version: 3.13.3
