apiVersion: v1
kind: Secret
metadata:
    name: actual-horizon-secrets
    namespace: apps
stringData:
    actual-budget-id: ENC[AES256_GCM,data:T6AfPF9ehxRGZw00srFDpVGWaacakK7/tBOXZnUqBe3IxM0Z,iv:3+WL1j+2LABGY4UAMjSgGNtQ0Zi6ClLLQ9mSGMRPNAg=,tag:T9OoICLorscObzxzcqZb+A==,type:str]
    actual-password: ENC[AES256_GCM,data:aZ6Byc1cUAmjq7pc3k0w7EjC+PLPxB6QIRpISCYcTBcHQA2P4dsSSkFQzy9cDJrJHWY6+vVD3MF9Z/cjJXD6fA==,iv:Icaev1enfqby2cPmQjdz0MoDFsYMPetAiL1pTM1qHso=,tag:n4uTMKea31lXNoGcQ/Q9lw==,type:str]
    actual-server-url: ENC[AES256_GCM,data:7eV4Dzfap8sMwAH7jxuv+OLw/9OTPO+wP31mwTw9PC13tAhJnNZLe8/NA+sSI1kOuXoP+Q==,iv:QMF35F7NforX7yTPkRMkMZlximxCi6baJQ27J8E8NPs=,tag:uHtFqTJoVHk2Ct1px1DP/g==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eTlqa2tOK1VuT0VkZ0kv
            aTdGaTFBMjFEYy9FMS9EeTJ1eGJKODdrVkZVCm9WZU91VDhId1hzQTRmcFlLTm1U
            a1pmYXp4cnJwSlY2Z3FsalcrYjNYdjAKLS0tIENxbFEzaUsxUVU3cndVM2RiSm54
            SEtZcFMrMkRWdHFnZEJjWWN0VEhzZE0KfI0heQjUSAMY8TOqijji7tbi+KbDvrd6
            0hSJQyPufHWtOMgFr40Nr4AoMm1YGEJQHthqNGI1mQtMjd4GBAU72Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T21:49:38Z"
    mac: ENC[AES256_GCM,data:YYfomWIKlekv4RGwDC02UX7UXIzOkQudWPCMzlRNxQxgB3JC0W5S/c7fYlNZqhNNmdn3wB3HtQ3HfnbiHNHhLna6I3P2xq7J7UPHxUSjPnq3pqJVcaF0nCJt6N6m4cWYclF858vOLsRtissRb5n9oBC5vvUTuYQ+kxqAZlp0ZZA=,iv:jV5hH8ObyjCWB1k5cUm1bJh9gsUV0e3n+bW7m9QgUdY=,tag:WGeELGjRWuJvmhW+gNnEWA==,type:str]
    version: 3.13.3
