apiVersion: v1
kind: Secret
metadata:
    name: llm-gateway-secrets
    namespace: apps
    labels:
        app.kubernetes.io/name: llm-gateway
        app.kubernetes.io/component: application
stringData:
    master-key: ENC[AES256_GCM,data:5xOgP/T2PU4Gx8/4zaVUR28tCbbNr9p9tSdxJQcCnS1Tvy0AWhRqiSalgxuOliEgA2x7,iv:nZ6o4/mXQrS0s+tn6ghlJ8aHpDJWOtWBC0QdP9dfyWc=,tag:zNZAWw9cwQWB3bbIImERuA==,type:str]
    salt-key: ENC[AES256_GCM,data:gbiP0PDF9AQANMYdLRQZfbNShZdKYmN57dBSjFGl6uMZgbhfkvCTQrltV1k=,iv:PrZ9h7Fx2AdoWUrGpcmZEN/skjJ5G3OI8i/AYoinkQo=,tag:6Z4ZKSOk3JAmzjWpERJYcg==,type:str]
    postgres-password: ENC[AES256_GCM,data:Jqsqn35+cGdZ/GbO0mtF3Nvs+3wMOrJ9CrP2DpDuR2c=,iv:bQWYOXgOLZOsP59joCGUvhJhJOyqyPbb5fU5nrjL5/c=,tag:v34Zp80PLwEURq9Ey5U29A==,type:str]
    database-url: ENC[AES256_GCM,data:vBUMIeSdc0KnBY3qsRdJ200PQfq7AHL0go/j7mXT6Jnm06LQzc7tdN0GbYznz8tYzZ5g4okiExmARpE8bAqDAAVVqVrO5HgCIe4qyvWHuB6a42YVrK4nPmyKcXXsnx2nCsmNKZ1fauAZJuDPzuDLsA==,iv:URsWyycGdb/uwF437TrNqUSmjYzS3JOMa1vRg42gqxs=,tag:k2WbI0eU1qnRqqoOV0HKXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNzV6Mk0xbk81YURIcFNm
            eU9vS3AwSnRYVHEwS3Y2VmIrTWxtWUk5a3lRCkkvb1htcHk2WXBWeTFSelZjRTRB
            T1NqMDE5dlpjVzQ3OE5aNFZNMEM2VUUKLS0tIHRocG82ajZGU3VVbEU1VitIamRt
            M3JBVm9sQXF6RGNnVkIxRWJBdWhZb3MKH4X7tM0HsqDXaKEgsxfMjYyJgjpO9M6C
            kwgl0qEQlxnIcLO2J7zTsLWz9OwwqGHq170nkUHV1TLn0T6mN7n87g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T17:50:34Z"
    mac: ENC[AES256_GCM,data:Lrx2a2u/xh4Sr+RsrNhQzCjbHkVUVdqBr03RqolWeTB/ykFSuru+aIGwS/GP8N2jqmnpsPVINtxYwCjWkeFdsngVRooimQin18thc+cm8prtoq4OCN8PvOVQrMb6M+fOcsDZ1Xhel6GL5gRf5u5ZEDgLZuKjUG9FzpvItjPHSLw=,iv:i0HaPVmO3rFioOF93qeNfy8Xkc0Ln4k3GgqQI/N6bRI=,tag:a3ycO7jFyMwCKlc8rFCdRQ==,type:str]
    version: 3.13.3
