apiVersion: v1
kind: Secret
metadata:
    name: llm-gateway-secrets
    namespace: apps
    labels:
        app.kubernetes.io/name: llm-gateway
        app.kubernetes.io/component: application
stringData:
    master-key: ENC[AES256_GCM,data:vHizp57mAngOO6/+gxlN3cwUJ6/wGuQQD6D98WwNejSsO3EZufdBgNWlPL6mv/Zr9+Qc,iv:aiV/QiI8tHmN4iOFxLeE3lGgP5o7g60fgosR/wKsovc=,tag:08WkFtH2odaBnw3+HtWWxQ==,type:str]
    salt-key: ENC[AES256_GCM,data:e99WpR98BZvVikoLEl+j6DykDzC/NnRMeJo+4cFjOQBNQXknpkM6AEQzN/0=,iv:3yt7KzjZR57wml+kvfW5mkNX4sLZTqNRh8Uh4WUWz8Y=,tag:+rj0jnoi8O0oh3dj3+/IZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQWZZQ0w3UEJuZHc5dlRw
            eDBQbFU0cjlOa2V1NGNnREQ4bUVZam5mU0NjCmtWalhGU2EwUlBEZjRlWjV6S0hp
            b0phcW1sczJFQkxWODNNa0t5YjV4ZTQKLS0tIEhmS3o3N0t0VDlUODdjQWNmN2tY
            dGZuZmU3NncxRGVNQmkrK0ZZYUlGM2sKmT5+uXEL+5YoHcJ2a077POkK+ju+KuDC
            aGErpBrpE6TQgKsudoqRA6MDwBjN+XWEYvzfjgDO9MXAQUmSrD+qww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T17:14:04Z"
    mac: ENC[AES256_GCM,data:naeMHmAWGrEgBMKO1VB+NpkASKUY/WYPqjh2hoaQon8Cw0boAFpV8V3eUQ2R9FhG3R2rH9mvkIXE53bgkqUNyT2x7pB78T4w5DUPORrFwoBJhE3XIt3gmJruy203FLTk7CpFa4BVvbeofkX42csxKSUO+/tX5lWwEb2Yzlf9ABQ=,iv:6Xb+mjVsfW7AEdIIDD/GaHmAygTjnhpI9rjlijIjwns=,tag:b6tf07owhC888y5eHVfzYQ==,type:str]
    version: 3.13.3
