apiVersion: v1
kind: Secret
metadata:
    name: llm-gateway-secrets
    namespace: apps
    labels:
        app.kubernetes.io/name: llm-gateway
        app.kubernetes.io/component: application
stringData:
    master-key: ENC[AES256_GCM,data:fhDe2dYA2oZSCaj6AOE4WUsNdR4FGCecCCu+LMdIwINQ5XaIc/Ykz5kNR6thy1G8ouED,iv:3Pyjy80ILM6Q2X9ApSBIXWvpqT3dgTT4K+VGg7sCtfw=,tag:3v2y7F92RtZhPHbilqQYxw==,type:str]
    salt-key: ENC[AES256_GCM,data:DsMzzfY7gx6P42z4+EH/4ysj/hcvnsHO8Qq5L3aqvaGlNXXuvSavWkk1K1A=,iv:DLSpbik7H3SEaz/JWW94nZc3HEEGGPEwQq9Uq/aKZWE=,tag:CGYaZfYDxDbSQJwRMAEHTA==,type:str]
    postgres-password: ENC[AES256_GCM,data:quzfNn0artBdnIUoBS0d8mhuDictu980hI8W8eN5l24=,iv:TJ+UOeXf3fqOmeJPLXgWQcASt4zotT2cfJOuv1bbmoo=,tag:wobluItOUv/YX5qRnoi6hg==,type:str]
    database-url: ENC[AES256_GCM,data:wvbd4ScIEMceh8mrSFKrQAuVHGvYZbRaibvMDbpuVXSE2mjEhvs1Bf7mcqJ0WzqSg8EWPEC4N2UIvlGtcGeuE9bsI+9Shea6sdQbs1jXtOkzwjGoUqOBEBf6c3v/dR/ccq4HBON9mSDSq1/tQ3ge0A==,iv:PrgJa/Hm8kN57nE8TEcZFZuvNSCjp4d1HEFULnuQtKA=,tag:NvZ8f9UljL9M/ztvwLWdRA==,type:str]
    oidc-client-secret: ENC[AES256_GCM,data:RqMYp1HyX+MYbjaoryjBs4UFJUHKrS0luiEfpp5SOszn+KpH9WQGOmrudmY7jenLFzs=,iv:J9fJqFHs+bjxaRElqo/7gogIqbISePmoWKam6dkaRE4=,tag:w7wIbAR94lugN3IZyxjGkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArU1BzSGFLRXh4RHppZ05h
            aDdDQTlWNjg5b1hranRkenRPeEJqZjdCVlRNCm9mbUhwbWlQMFgrcXBBNTRaOTN2
            VFlOY3VZV2U0MnhObVVkb0JlUktiNTQKLS0tIHJzWUtJK0NDelRYUDkzcFFMQVJW
            N1BnOExZdkpUTHBWc2NKeUh3RFduTU0KEPoqpvhKmkmOAy452aYqnHFReEB9HIad
            hbWkUzFAtrZGOp9Ntzramn7lF3MNY38Tx60UzwBmjUee6qnly/p+4w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnzcjl2fzkcxm6u2mjrm8w902edn9vtym9hr8a5ve66leayau99qs9xna5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T19:19:12Z"
    mac: ENC[AES256_GCM,data:GADOEl/dqkIFnEL0/0p6Mw9Q2260QpQYK0d4Sy+VOKz8flty6ytpPQBb7FlXwJkw1iIOeRwKKYV4BUV1rE3QyCpqF9/vPNq0ifzF4oERDj6knyLiKFYA7+q2IL/HwkLbf1kTM3/nSk8FleqUxGmZIB0QQK3zSwGj7qxoIsXUM6s=,iv:hFr6LQHoH0RYkpar0OnKS/2XyokSHtdwtaWoUZSwTcg=,tag:4qRhoqgZgEwR1md03y1SNQ==,type:str]
    version: 3.13.3
